GameplayCore Plugin: UEquipmentSystemComponent Class Reference
UEquipmentSystemComponent Class Reference
Component managing equipment system functionality for actors.
#include <EquipmentSystemComponent.h>
Public Member Functions
UEquipmentSystemComponent (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
virtual bool ReplicateSubobjects (UActorChannel *Channel, FOutBunch *Bunch, FReplicationFlags *RepFlags) override
virtual void ReadyForReplication () override
virtual void InitializeComponent () override
virtual void UninitializeComponent () override
FEquipmentResult TryEquipItem (UItemInstance *ItemInstance)
FEquipmentResult TryEquipItemOnSlot (UItemInstance *ItemInstance, const FGameplayTag &SlotTag)
bool TryUnequipItem (UItemInstance *ItemInstance, FGameplayTag &OutFailureReason)
bool TryUnequipSlot (const FGameplayTag SlotTag, FGameplayTag &OutFailureReason)
bool TrySwapSlots (const FGameplayTag &SlotA, const FGameplayTag &SlotB, FGameplayTag &OutFailureReason)
bool IsSlotBlocked (const FGameplayTag &SlotTag, bool bExact=false) const
const FDynamicEquipmentSlot * FindSlot (const FGameplayTag &SlotTag) const
TMap< FGameplayTag, FDynamicEquipmentSlot > GetSlotMap () const
const FGameplayTag & GetSlotForItem (UItemInstance *ItemInstance)
UItemInstance * GetItemInSlot (const FGameplayTag &SlotTag)
UEquipmentInstance * GetEquipmentInSlot (const FGameplayTag &SlotTag)
void GetEquippedItems (TMap< FGameplayTag, UItemInstance * > &OutItems) const
UEquipmentInstance * GetInstanceOfType (const TSubclassOf< UEquipmentInstance > &InstanceClass)
template<typename T>
T * GetInstanceOfType () const
TArray< UEquipmentInstance * > GetAllInstancesOfType (const TSubclassOf< UEquipmentInstance > &InstanceClass)
template<typename T>
TArray< T * > GetAllInstancesOfType () const
UEquipmentDefinition * GetCachedDefinition (const TSubclassOf< UEquipmentDefinition > &Class) const
UEquipmentInstance * GetInstanceFromItem (UItemInstance *ItemInstance)
Public Attributes
FOnEquipmentChange OnEquipmentChanged
FOnEquipmentChange OnEquipmentEquipped
FOnEquipmentChange OnEquipmentUnequipped
Protected Member Functions
virtual void PostEquipmentEquipped (const FEquipmentChangeData &Data)
virtual void PostEquipmentUnequipped (const FEquipmentChangeData &Data)
virtual void PostEquipmentChanged (const FEquipmentChangeData &Data)
void LockSlots (const FGameplayTagContainer &Tags)
void UnlockSlots (const FGameplayTagContainer &Tags)
FEquipmentResult Internal_ProcessEquip (UItemInstance *ItemInstance, const FGameplayTag &TargetSlot, const UEquipmentDefinition *Definition)
bool Internal_ProcessUnequip (const FGameplayTag &SlotTag, FGameplayTag &OutFailureReason, bool bPreserveItem=false)
FEquipmentResult Internal_EquipOnSlot (const FGameplayTag &SlotTag, UItemInstance *ItemInstance, const UEquipmentDefinition *Definition)
Protected Attributes
FEquipmentList EquipmentList
TObjectPtr< UEquipmentCache > Cache
TObjectPtr< UEquipmentSlotMapData > SlotMapData
TMap< FGameplayTag, FDynamicEquipmentSlot > SlotMapRuntime
FGameplayTagCountContainer BlockedSlots
Detailed Description
Component managing equipment system functionality for actors.
See also
UActorComponent
Manages equipment slots, item equipping/unequipping, and equipment instances. Provides runtime validation of equipment changes through policies, maintains a dynamic slot system, and handles replication of equipped items. Supports blocking/unblocking equipment slots and broadcasting equipment change events.
Definition at line 36 of file EquipmentSystemComponent.h.
Constructor & Destructor Documentation
UEquipmentSystemComponent()
UEquipmentSystemComponent::UEquipmentSystemComponent (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get()) explicit
Definition at line 22 of file EquipmentSystemComponent.cpp.
    : Super(ObjectInitializer), EquipmentList(this)
{
    PrimaryComponentTick.bCanEverTick = false;
    bWantsInitializeComponent = true;
    SetIsReplicatedByDefault(true);
    bReplicateUsingRegisteredSubObjectList = true;
}
Member Function Documentation
FindSlot()
const FDynamicEquipmentSlot * UEquipmentSystemComponent::FindSlot (const FGameplayTag & SlotTag) const
Finds a slot by its tag
Parameters
SlotTag The tag of the slot to find
Returns
Pointer to the found slot, or nullptr if not found
Definition at line 267 of file EquipmentSystemComponent.cpp.
{
    return SlotMapRuntime.Find(SlotTag);
}
Referenced by TryEquipItemOnSlot().
GetAllInstancesOfType() [1/2]
template<typename T> TArray< T * > UEquipmentSystemComponent::GetAllInstancesOfType () const
Gets all instances of specified equipment type using templates
Template Parameters
T The equipment instance type to find
Returns
Array of all instances of type T
Definition at line 278 of file EquipmentSystemComponent.h.
{
    TArray<T*> Instances;
    for (const FEquipmentEntry& Entry : EquipmentList.Entries)
    {
        if (UEquipmentInstance* Instance = Entry.Instance)
        {
            if (Instance->IsA<T>())
            {
                Instances.Add(Cast<T>(Instance));
            }
        }
    }
    return Instances;
}
References EquipmentList.
GetAllInstancesOfType() [2/2]
TArray< UEquipmentInstance * > UEquipmentSystemComponent::GetAllInstancesOfType (const TSubclassOf< UEquipmentInstance > & InstanceClass)
Gets all instances of the specified equipment type.
Parameters
InstanceClass The class of the equipment instances to find.
Returns
An array of UEquipmentInstances of the specified type.
Definition at line 333 of file EquipmentSystemComponent.cpp.
{
    TArray<UEquipmentInstance*> Results;
    for (const FEquipmentEntry& Entry : EquipmentList.Entries)
    {
        if (UEquipmentInstance* Instance = Entry.Instance)
        {
            if (Instance->IsA(InstanceClass))
            {
                Results.Add(Instance);
            }
        }
    }
    return Results;
}
References EquipmentList.
GetCachedDefinition()
UEquipmentDefinition * UEquipmentSystemComponent::GetCachedDefinition (const TSubclassOf< UEquipmentDefinition > & Class) const
Retrieves a cached equipment definition
Parameters
Class The class of equipment definition to retrieve
Returns
The cached equipment definition instance, or nullptr if not found
Definition at line 349 of file EquipmentSystemComponent.cpp.
{
    if (IsValid(Cache))
    {
        return Cache->GetCachedDefinition(Class);
    }
    if (IsValid(Class))
    {
        return NewObject<UEquipmentDefinition>(GetOuter(), Class);
    }
    return nullptr;
}
References Cache.
Referenced by TryEquipItem(), TryEquipItemOnSlot(), and TrySwapSlots().
GetEquipmentInSlot()
UEquipmentInstance * UEquipmentSystemComponent::GetEquipmentInSlot (const FGameplayTag & SlotTag)
Gets the equipment instance in a specific slot
Parameters
SlotTag The slot to check
Returns
The equipment in the slot, or nullptr if empty
Definition at line 296 of file EquipmentSystemComponent.cpp.
{
    if (SlotMapRuntime.Contains(SlotTag))
    {
        return SlotMapRuntime.FindChecked(SlotTag).EquipmentInstance;
    }
    return nullptr;
}
GetEquippedItems()
void UEquipmentSystemComponent::GetEquippedItems (TMap< FGameplayTag, UItemInstance * > & OutItems) const
Gets all currently equipped items
Parameters
OutItems Map of slot tags to equipped items
Definition at line 306 of file EquipmentSystemComponent.cpp.
{
    OutItems.Empty();
    for (const auto& [SlotTag, SlotData] : SlotMapRuntime)
    {
        if (SlotData.ItemInstance)
        {
            OutItems.Add(SlotTag, SlotData.ItemInstance);
        }
    }
}
GetInstanceFromItem()
UEquipmentInstance * UEquipmentSystemComponent::GetInstanceFromItem (UItemInstance * ItemInstance)
Gets the equipment instance of the associated ItemInstance
Parameters
ItemInstance The instance of the source item
Returns
The equipment instance associated with the item, or nullptr if not found
Definition at line 362 of file EquipmentSystemComponent.cpp.
{
    for (FEquipmentEntry& Entry : EquipmentList.Entries)
    {
        if (UEquipmentInstance* Instance = Entry.Instance)
        {
            if (Instance->GetSourceItem() == ItemInstance)
            {
                return Instance;
            }
        }
    }
    return nullptr;
}
References EquipmentList.
GetInstanceOfType() [1/2]
template<typename T> T * UEquipmentSystemComponent::GetInstanceOfType () const
Gets an instance of specified equipment type using templates
Template Parameters
T The equipment instance type to find
Returns
The first found instance of type T, or nullptr if none found
Definition at line 272 of file EquipmentSystemComponent.h.
{
    return Cast<T>(GetInstanceOfType(T::StaticClass()));
}
References GetInstanceOfType().
GetInstanceOfType() [2/2]
UEquipmentInstance * UEquipmentSystemComponent::GetInstanceOfType (const TSubclassOf< UEquipmentInstance > & InstanceClass)
Gets an instance of the specified equipment type.
Parameters
InstanceClass The class of the equipment instance to find.
Returns
The first found UEquipmentInstance of the specified type.
Definition at line 318 of file EquipmentSystemComponent.cpp.
{
    for (const FEquipmentEntry& Entry : EquipmentList.Entries)
    {
        if (UEquipmentInstance* Instance = Entry.Instance)
        {
            if (Instance->IsA(InstanceClass))
            {
                return Instance;
            }
        }
    }
    return nullptr;
}
References EquipmentList.
Referenced by GetInstanceOfType().
GetItemInSlot()
UItemInstance * UEquipmentSystemComponent::GetItemInSlot (const FGameplayTag & SlotTag)
Gets the item instance equipped in a specific slot
Parameters
SlotTag The slot to check
Returns
The item in the slot, or nullptr if empty
Definition at line 287 of file EquipmentSystemComponent.cpp.
{
    if (SlotMapRuntime.Contains(SlotTag))
    {
        return SlotMapRuntime.FindChecked(SlotTag).ItemInstance;
    }
    return nullptr;
}
GetLifetimeReplicatedProps()
void UEquipmentSystemComponent::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override virtual
Definition at line 32 of file EquipmentSystemComponent.cpp.
{
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(ThisClass, EquipmentList);
}
GetSlotForItem()
const FGameplayTag & UEquipmentSystemComponent::GetSlotForItem (UItemInstance * ItemInstance)
Gets the slot tag where an item is currently equipped
Parameters
ItemInstance The item to find the slot for
Returns
The tag of the slot containing the item
Definition at line 272 of file EquipmentSystemComponent.cpp.
{
    if (IsValid(ItemInstance))
    {
        for (const auto& [SlotTag, SlotData] : SlotMapRuntime)
        {
            if (SlotData.ItemInstance == ItemInstance)
            {
                return SlotTag;
            }
        }
    }
    return FGameplayTag::EmptyTag;
}
Referenced by TryUnequipItem().
GetSlotMap()
TMap< FGameplayTag, FDynamicEquipmentSlot > UEquipmentSystemComponent::GetSlotMap () const inline
Gets the current runtime slot map
Returns
Map of all equipment slots
Definition at line 125 of file EquipmentSystemComponent.h.
{ return SlotMapRuntime; }
References GetSlotMap().
Referenced by GetSlotMap().
InitializeComponent()
void UEquipmentSystemComponent::InitializeComponent () override virtual
Definition at line 71 of file EquipmentSystemComponent.cpp.
{
    Super::InitializeComponent();
    // Cache initialization
    Cache = NewObject<UEquipmentCache>(this, "Cache");
    if (IsValid(SlotMapData))
    {
        for (const FSlotDefinition& Def : SlotMapData->Slots)
        {
            if (Def.SlotTag.IsValid())
            {
                SlotMapRuntime.Add(Def.SlotTag, FDynamicEquipmentSlot{});
            }
        }
    }
}
Internal_EquipOnSlot()
FEquipmentResult UEquipmentSystemComponent::Internal_EquipOnSlot (const FGameplayTag & SlotTag, UItemInstance * ItemInstance, const UEquipmentDefinition * Definition) protected
Definition at line 530 of file EquipmentSystemComponent.cpp.
{
    SCOPE_CYCLE_COUNTER(STAT_Equipment_EquipOnSlot);
    // Create a new equipment instance and add it to our list
    FEquipmentResult Result = EquipmentList.Add(Definition->GetClass(), ItemInstance);
    if (!Result.Succeeded())
    {
        return Result;
    }
    // Notify the instance it has been equipped
    Result.Instance->OnEquipped();
    // Setup replication if needed
    if (IsUsingRegisteredSubObjectList() && IsReadyForReplication())
    {
        AddReplicatedSubObject(Result.Instance);
    }
    // Update the runtime slot with the new equipment
    FDynamicEquipmentSlot& RuntimeSlot = SlotMapRuntime.FindChecked(SlotTag);
    RuntimeSlot.SlotTag = SlotTag;
    RuntimeSlot.ItemInstance = ItemInstance;
    RuntimeSlot.EquipmentInstance = Result.Instance;
    // Apply any slot blocking from the equipment policy
    if (const USlotPolicy* Policy = Definition->SlotPolicy)
    {
        LockSlots(Policy->GetBlockedSlotTags());
    }
    return Result;
}
Internal_ProcessEquip()
FEquipmentResult UEquipmentSystemComponent::Internal_ProcessEquip (UItemInstance * ItemInstance, const FGameplayTag & TargetSlot, const UEquipmentDefinition * Definition) protected
Definition at line 402 of file EquipmentSystemComponent.cpp.
{
    SCOPE_CYCLE_COUNTER(STAT_Equipment_ProcessEquip);
    FEquipmentResult Result;
    // Validate input parameters
    if (!IsValid(ItemInstance))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process equipment of a null item instance."));
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_NullItem;
        return Result;
    }
    if (!IsValid(Definition))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process equipment of %s with a null equipment definition."), *GetNameSafe(ItemInstance));
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_MissingDefinition;
        return Result;
    }
    // Validate slot exists in our equipment system
    if (!FindSlot(TargetSlot))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process equipment of %s as %s but did not found slot %s in the slot map."), *GetNameSafe(ItemInstance), *GetNameSafe(Definition), *TargetSlot.ToString());
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_SlotNotFound;
        return Result;
    }
    // Check if slot is currently blocked by another item
    if (IsSlotBlocked(TargetSlot, true))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process equipment of %s as %s on slot %s but the slot is blocked."), *GetNameSafe(ItemInstance), *GetNameSafe(Definition), *TargetSlot.ToString());
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_SlotBlocked;
        return Result;
    }
    // Check if the slot policy allows this equipment
    if (const USlotPolicy* Policy = Definition->SlotPolicy)
    {
        if (!Policy->CanEquipItem(ItemInstance, TargetSlot, this))
        {
            Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_PolicyRefused;
            return Result;
        }
    }
    // Perform the actual equipment operation
    Result = Internal_EquipOnSlot(TargetSlot, ItemInstance, Definition);
    if (!Result.Succeeded())
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process equipment of %s as %s on slot %s but failed to instantiate the equipment."), *GetNameSafe(ItemInstance), *GetNameSafe(Definition), *TargetSlot.ToString());
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_Internal;
        return Result;
    }
    return Result;
}
Internal_ProcessUnequip()
bool UEquipmentSystemComponent::Internal_ProcessUnequip (const FGameplayTag & SlotTag, FGameplayTag & OutFailureReason, bool bPreserveItem = false) protected
Definition at line 460 of file EquipmentSystemComponent.cpp.
{
    SCOPE_CYCLE_COUNTER(STAT_Equipment_ProcessUnequip);
    // Validate that the slot exists in our runtime map
    if (!SlotMapRuntime.Contains(SlotTag))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process un-equipment but did not found slot %s in the slot map."), *SlotTag.ToString());
        OutFailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_SlotNotFound;
        return false;
    }
    auto& SlotData = SlotMapRuntime.FindChecked(SlotTag);
    // Check if there's actually something equipped in this slot
    if (!IsValid(SlotData.ItemInstance) || !IsValid(SlotData.EquipmentInstance))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process un-equipment but the slot %s is empty."), *SlotTag.ToString());
        OutFailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_SlotEmpty;
        return false;
    }
    // Validate that the item has the required equippable fragment
    const UItemFragment_Equippable* Frag = SlotData.ItemInstance->FindFragmentByClass<UItemFragment_Equippable>();
    if (!Frag || !Frag->EquipmentDefinition)
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process un-equipment on the slot %s but did found a non-equipable item."), *SlotTag.ToString());
        OutFailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_MissingDefinition;
        return false;
    }
    // Get and validate the equipment definition
    const UEquipmentDefinition* Def = GetCachedDefinition(Frag->EquipmentDefinition);
    if (!IsValid(Def))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to process un-equipment on the slot %s but impossible to get the equipment definition."), *SlotTag.ToString());
        OutFailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_Internal;
        return false;
    }
    // Remove any slot blocking applied by this equipment's policy
    if (const USlotPolicy* Policy = Def->SlotPolicy)
    {
        UnlockSlots(Policy->GetBlockedSlotTags());
    }
    // Store the instance before clearing slot data
    UEquipmentInstance* Instance = SlotData.EquipmentInstance;
    if (!bPreserveItem)
    {
        SlotData.ItemInstance = nullptr;
    }
    SlotData.EquipmentInstance = nullptr;
    // Clean up the equipment instance
    if (IsValid(Instance))
    {
        if (IsUsingRegisteredSubObjectList())
        {
            RemoveReplicatedSubObject(Instance);
        }
        Instance->OnUnequipped();
        EquipmentList.Remove(Instance, OutFailureReason);
    }
    OutFailureReason = FGameplayTag::EmptyTag;
    return true;
}
IsSlotBlocked()
bool UEquipmentSystemComponent::IsSlotBlocked (const FGameplayTag & SlotTag, bool bExact = false) const
Checks if a slot is currently blocked from equipment changes
Parameters
SlotTag The slot to check
bExact If true, only checks for exact tag match
Returns
True if the slot is blocked
Definition at line 258 of file EquipmentSystemComponent.cpp.
{
    if (bExact)
    {
        return BlockedSlots.GetTagCount(SlotTag) > 0;
    }
    return BlockedSlots.HasMatchingGameplayTag(SlotTag);
}
LockSlots()
void UEquipmentSystemComponent::LockSlots (const FGameplayTagContainer & Tags) protected
Locks specified equipment slots from being modified
Parameters
Tags Container of slot tags to lock
Definition at line 392 of file EquipmentSystemComponent.cpp.
{
    BlockedSlots.UpdateTagCount(Tags, 1);
}
PostEquipmentChanged()
void UEquipmentSystemComponent::PostEquipmentChanged (const FEquipmentChangeData & Data) protected virtual
Called after any equipment change occurs
Parameters
Data The equipment change data
Definition at line 387 of file EquipmentSystemComponent.cpp.
{
    OnEquipmentChanged.Broadcast(Data);
}
References OnEquipmentChanged.
PostEquipmentEquipped()
void UEquipmentSystemComponent::PostEquipmentEquipped (const FEquipmentChangeData & Data) protected virtual
Called after equipment is successfully equipped
Parameters
Data The equipment change data
Definition at line 377 of file EquipmentSystemComponent.cpp.
{
    OnEquipmentEquipped.Broadcast(Data);
}
References OnEquipmentEquipped.
PostEquipmentUnequipped()
void UEquipmentSystemComponent::PostEquipmentUnequipped (const FEquipmentChangeData & Data) protected virtual
Called after equipment is successfully unequipped
Parameters
Data The equipment change data
Definition at line 382 of file EquipmentSystemComponent.cpp.
{
    OnEquipmentUnequipped.Broadcast(Data);
}
References OnEquipmentUnequipped.
ReadyForReplication()
void UEquipmentSystemComponent::ReadyForReplication () override virtual
Definition at line 54 of file EquipmentSystemComponent.cpp.
{
    Super::ReadyForReplication();
    // Register all equipment instances ready for replication with the actor component
    if (IsUsingRegisteredSubObjectList())
    {
        for (const FEquipmentEntry& Entry : EquipmentList.Entries)
        {
            if (UEquipmentInstance* Instance = Entry.Instance; IsValid(Instance))
            {
                AddReplicatedSubObject(Instance);
            }
        }
    }
}
ReplicateSubobjects()
bool UEquipmentSystemComponent::ReplicateSubobjects (UActorChannel * Channel, FOutBunch * Bunch, FReplicationFlags * RepFlags) override virtual
Definition at line 39 of file EquipmentSystemComponent.cpp.
{
    bool bReplicated = Super::ReplicateSubobjects(Channel, Bunch, RepFlags);
    for (FEquipmentEntry& Entry : EquipmentList.Entries)
    {
        if (UEquipmentInstance* Instance = Entry.Instance; IsValid(Instance))
        {
            bReplicated |= Channel->ReplicateSubobject(Instance, *Bunch, *RepFlags);
        }
    }
    return bReplicated;
}
TryEquipItem()
FEquipmentResult UEquipmentSystemComponent::TryEquipItem (UItemInstance * ItemInstance)
Attempts to equip an item in the first available slot
Parameters
ItemInstance The item to equip
Returns
True if the item was successfully equipped
Definition at line 110 of file EquipmentSystemComponent.cpp.
{
    FEquipmentResult Result;
    if (!IsValid(ItemInstance))
    {
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_NullItem;
        return Result;
    }
    const UItemFragment_Equippable* Frag = ItemInstance->FindFragmentByClass<UItemFragment_Equippable>();
    if (!Frag || !Frag->EquipmentDefinition)
    {
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_MissingDefinition;
        return Result;
    }
    const UEquipmentDefinition* Definition = GetCachedDefinition(Frag->EquipmentDefinition);
    const FGameplayTag SlotTag = Definition->SlotTag;
    return TryEquipItemOnSlot(ItemInstance, Definition->SlotTag);
}
References UItemFragment_Equippable::EquipmentDefinition, UItemInstance::FindFragmentByClass(), GetCachedDefinition(), and TryEquipItemOnSlot().
TryEquipItemOnSlot()
FEquipmentResult UEquipmentSystemComponent::TryEquipItemOnSlot (UItemInstance * ItemInstance, const FGameplayTag & SlotTag)
Attempts to equip an item in a specific slot
Parameters
ItemInstance The item to equip
SlotTag The target slot to equip the item in
Returns
True if the item was successfully equipped
Definition at line 132 of file EquipmentSystemComponent.cpp.
{
    FEquipmentResult Result;
    if (!IsValid(ItemInstance))
    {
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_NullItem;
        return Result;
    }
    const UItemFragment_Equippable* Frag = ItemInstance->FindFragmentByClass<UItemFragment_Equippable>();
    if (!Frag || !Frag->EquipmentDefinition)
    {
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_MissingDefinition;
        return Result;
    }
    const UEquipmentDefinition* Definition = GetCachedDefinition(Frag->EquipmentDefinition);
    // De-equip the current slot if necessary
    if (const FDynamicEquipmentSlot* CurrentSlot = FindSlot(SlotTag))
    {
        if (IsValid(CurrentSlot->ItemInstance))
        {
            if (!Internal_ProcessUnequip(SlotTag, Result.FailureReason))
            {
                return Result;
            }
        }
    }
    return Internal_ProcessEquip(ItemInstance, SlotTag, Definition);
}
References UItemFragment_Equippable::EquipmentDefinition, UItemInstance::FindFragmentByClass(), FindSlot(), and GetCachedDefinition().
Referenced by TryEquipItem().
TrySwapSlots()
bool UEquipmentSystemComponent::TrySwapSlots (const FGameplayTag & SlotA, const FGameplayTag & SlotB, FGameplayTag & OutFailureReason)
Attempts to swap items between two equipment slots
Parameters
SlotA First slot to swap
SlotB Second slot to swap
OutFailureReason Contains the reason if the operation fails
Returns
True if the slots were successfully swapped
Definition at line 188 of file EquipmentSystemComponent.cpp.
{
    // First validate that both slots exist in our runtime map
    if (!SlotMapRuntime.Contains(SlotA) || !SlotMapRuntime.Contains(SlotB))
    {
        OutFailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_SlotNotFound;
        return false;
    }
    const FDynamicEquipmentSlot& SlotDataA = SlotMapRuntime.FindChecked(SlotA);
    const FDynamicEquipmentSlot& SlotDataB = SlotMapRuntime.FindChecked(SlotB);
    // If both slots are empty, no swap is needed
    if (!IsValid(SlotDataA.ItemInstance) && !IsValid(SlotDataB.ItemInstance))
    {
        return true;
    }
    // Store slot A contents before we start moving things around
    UItemInstance* TempItemA = SlotDataA.ItemInstance;
    UEquipmentInstance* TempEquipA = SlotDataA.EquipmentInstance;
    // First phase: Unequip both slots while preserving the item references
    if (IsValid(SlotDataA.ItemInstance))
    {
        if (!Internal_ProcessUnequip(SlotA, OutFailureReason, true))
        {
            return false;
        }
    }
    if (IsValid(SlotDataB.ItemInstance))
    {
        if (!Internal_ProcessUnequip(SlotB, OutFailureReason, true))
        {
            // On failure, restore slot A to its original state
            if (IsValid(TempItemA))
            {
                if (const UItemFragment_Equippable* Frag = TempItemA->FindFragmentByClass<UItemFragment_Equippable>(); Frag->EquipmentDefinition)
                {
                    Internal_ProcessEquip(TempItemA, SlotA, GetCachedDefinition(Frag->EquipmentDefinition));
                }
            }
            return false;
        }
    }
    // Second phase: Cross-equip items into their new slots
    bool bSuccess = true;
    if (IsValid(SlotDataB.ItemInstance))
    {
        if (const UItemFragment_Equippable* Frag = SlotDataB.ItemInstance->FindFragmentByClass<UItemFragment_Equippable>(); Frag->EquipmentDefinition)
        {
            const FEquipmentResult Result = Internal_ProcessEquip(SlotDataB.ItemInstance, SlotA, GetCachedDefinition(Frag->EquipmentDefinition));
            bSuccess = Result.Succeeded();
        }
    }
    if (bSuccess && IsValid(TempItemA))
    {
        if (const UItemFragment_Equippable* Frag = TempItemA->FindFragmentByClass<UItemFragment_Equippable>(); Frag->EquipmentDefinition)
        {
            const FEquipmentResult Result = Internal_ProcessEquip(TempItemA, SlotB, GetCachedDefinition(Frag->EquipmentDefinition));
            bSuccess = Result.Succeeded();
        }
    }
    return bSuccess;
}
References UItemFragment_Equippable::EquipmentDefinition, UItemInstance::FindFragmentByClass(), and GetCachedDefinition().
TryUnequipItem()
bool UEquipmentSystemComponent::TryUnequipItem (UItemInstance * ItemInstance, FGameplayTag & OutFailureReason)
Attempts to unequip a currently equipped item
Parameters
ItemInstance The item to unequip
OutFailureReason Contains the reason if the operation fails
Returns
True if the item was successfully unequipped
Definition at line 165 of file EquipmentSystemComponent.cpp.
{
    if (!IsValid(ItemInstance))
    {
        OutFailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_NullItem;
        return false;
    }
    const FGameplayTag Slot = GetSlotForItem(ItemInstance);
    if (!Slot.IsValid())
    {
        OutFailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_SlotNotFound;
        return false;
    }
    return TryUnequipSlot(Slot, OutFailureReason);
}
References GetSlotForItem(), and TryUnequipSlot().
TryUnequipSlot()
bool UEquipmentSystemComponent::TryUnequipSlot (const FGameplayTag SlotTag, FGameplayTag & OutFailureReason)
Attempts to unequip whatever item is in the specified slot
Parameters
SlotTag The slot to unequip
OutFailureReason Contains the reason if the operation fails
Returns
True if the slot was successfully unequipped
Definition at line 183 of file EquipmentSystemComponent.cpp.
{
    return Internal_ProcessUnequip(SlotTag, OutFailureReason);
}
Referenced by TryUnequipItem().
UninitializeComponent()
void UEquipmentSystemComponent::UninitializeComponent () override virtual
Definition at line 90 of file EquipmentSystemComponent.cpp.
{
    TArray<FGameplayTag> SlotsToUnequip;
    for (const auto& Pair : SlotMapRuntime)
    {
        if (IsValid(Pair.Value.ItemInstance))
        {
            SlotsToUnequip.Add(Pair.Key);
        }
    }
    FGameplayTag FailureReason;
    for (const FGameplayTag& SlotTag : SlotsToUnequip)
    {
        TryUnequipSlot(SlotTag, FailureReason);
    }
    Super::UninitializeComponent();
}
UnlockSlots()
void UEquipmentSystemComponent::UnlockSlots (const FGameplayTagContainer & Tags) protected
Unlocks previously locked equipment slots
Parameters
Tags Container of slot tags to unlock
Definition at line 397 of file EquipmentSystemComponent.cpp.
{
    BlockedSlots.UpdateTagCount(Tags, -1);
}
Member Data Documentation
BlockedSlots
FGameplayTagCountContainer UEquipmentSystemComponent::BlockedSlots protected
Definition at line 268 of file EquipmentSystemComponent.h.
Cache
TObjectPtr<UEquipmentCache> UEquipmentSystemComponent::Cache protected
Equipment definitions cache. Not replicated
Definition at line 260 of file EquipmentSystemComponent.h.
Referenced by GetCachedDefinition().
EquipmentList
FEquipmentList UEquipmentSystemComponent::EquipmentList protected
The list of equipped items.
Definition at line 256 of file EquipmentSystemComponent.h.
Referenced by GetAllInstancesOfType(), GetAllInstancesOfType(), GetInstanceFromItem(), and GetInstanceOfType().
OnEquipmentChanged
FOnEquipmentChange UEquipmentSystemComponent::OnEquipmentChanged
Delegate dispatched when an item is equipped
Definition at line 245 of file EquipmentSystemComponent.h.
Referenced by PostEquipmentChanged().
OnEquipmentEquipped
FOnEquipmentChange UEquipmentSystemComponent::OnEquipmentEquipped
Broadcasts when equipment is equipped, providing the instance.
Definition at line 248 of file EquipmentSystemComponent.h.
Referenced by PostEquipmentEquipped().
OnEquipmentUnequipped
FOnEquipmentChange UEquipmentSystemComponent::OnEquipmentUnequipped
Broadcasts when equipment is unequipped, providing the instance.
Definition at line 251 of file EquipmentSystemComponent.h.
Referenced by PostEquipmentUnequipped().
SlotMapData
TObjectPtr<UEquipmentSlotMapData> UEquipmentSystemComponent::SlotMapData protected
Definition at line 263 of file EquipmentSystemComponent.h.
SlotMapRuntime
TMap<FGameplayTag, FDynamicEquipmentSlot> UEquipmentSystemComponent::SlotMapRuntime protected
Definition at line 266 of file EquipmentSystemComponent.h.
The documentation for this class was generated from the following files:
Source/EquipmentSystemCore/Public/Components/EquipmentSystemComponent.h
Source/EquipmentSystemCore/Private/Components/EquipmentSystemComponent.cpp