GameplayCore Plugin: UAbilitySystemComponentBase Class Reference
UAbilitySystemComponentBase Class Reference
This class extends the base UAbilitySystemComponent to provide additional functionality.
#include <AbilitySystemComponentBase.h>
Public Member Functions
UAbilitySystemComponentBase (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
virtual void InitAbilityActorInfo (AActor *InOwnerActor, AActor *InAvatarActor) override
virtual void NotifyAbilityEnded (FGameplayAbilitySpecHandle Handle, UGameplayAbility *Ability, bool bWasCancelled) override
void AbilityInputTagPressed (const FGameplayTag &InputTag)
void AbilityInputTagReleased (const FGameplayTag &InputTag)
void ProcessAbilityInput (float DeltaTime, bool bGamePaused)
void ClearAbilityInput ()
Protected Member Functions
void InitAbilitiesOnNewActorInfo ()
void TryActivateAbilitiesOnSpawn ()
virtual void AbilitySpecInputPressed (FGameplayAbilitySpec &Spec) override
virtual void AbilitySpecInputReleased (FGameplayAbilitySpec &Spec) override
Protected Attributes
TArray< FGameplayAbilitySpecHandle > InputPressedSpecHandles
TArray< FGameplayAbilitySpecHandle > InputReleasedSpecHandles
TArray< FGameplayAbilitySpecHandle > InputHeldSpecHandles
Friends
class UGameplayAbilityBase
Detailed Description
This class extends the base UAbilitySystemComponent to provide additional functionality.
See also
UAbilitySystemComponent
Definition at line 17 of file AbilitySystemComponentBase.h.
Constructor & Destructor Documentation
UAbilitySystemComponentBase()
UAbilitySystemComponentBase::UAbilitySystemComponentBase (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get())
Definition at line 9 of file AbilitySystemComponentBase.cpp.
    : Super(ObjectInitializer.Get())
{
}
Member Function Documentation
AbilityInputTagPressed()
void UAbilitySystemComponentBase::AbilityInputTagPressed (const FGameplayTag & InputTag)
Handles the pressing of an ability input tag.
Parameters
InputTag The input tag that was pressed.
Definition at line 48 of file AbilitySystemComponentBase.cpp.
{
    if (InputTag.IsValid())
    {
        for (const FGameplayAbilitySpec& AbilitySpec : ActivatableAbilities.Items)
        {
            if (AbilitySpec.Ability && (AbilitySpec.GetDynamicSpecSourceTags().HasTagExact(InputTag)))
            {
                InputPressedSpecHandles.AddUnique(AbilitySpec.Handle);
                InputHeldSpecHandles.AddUnique(AbilitySpec.Handle);
            }
        }
    }
}
References InputHeldSpecHandles, and InputPressedSpecHandles.
AbilityInputTagReleased()
void UAbilitySystemComponentBase::AbilityInputTagReleased (const FGameplayTag & InputTag)
Handles the release of an ability input tag.
Parameters
InputTag The input tag that was released.
Definition at line 63 of file AbilitySystemComponentBase.cpp.
{
    if (InputTag.IsValid())
    {
        for (const FGameplayAbilitySpec& AbilitySpec : ActivatableAbilities.Items)
        {
            if (AbilitySpec.Ability && (AbilitySpec.GetDynamicSpecSourceTags().HasTagExact(InputTag)))
            {
                InputReleasedSpecHandles.AddUnique(AbilitySpec.Handle);
                InputHeldSpecHandles.Remove(AbilitySpec.Handle);
            }
        }
    }
}
References InputHeldSpecHandles, and InputReleasedSpecHandles.
AbilitySpecInputPressed()
void UAbilitySystemComponentBase::AbilitySpecInputPressed (FGameplayAbilitySpec & Spec) override protected virtual
Handles when an ability spec input is pressed.
Parameters
Spec The ability spec that had its input pressed.
Definition at line 191 of file AbilitySystemComponentBase.cpp.
{
    Super::AbilitySpecInputPressed(Spec);
    // UE : We don't support UGameplayAbility::bReplicateInputDirectly.
    // Use replicated events instead so that the WaitInputPress ability task works.
    if (Spec.IsActive())
    {
        FPredictionKey OriginalPredictionKey;
        if (const UGameplayAbility* Instance = Spec.GetPrimaryInstance())
        {
            OriginalPredictionKey = Instance->GetCurrentActivationInfo().GetActivationPredictionKey();
        }
        // Invoke the InputPressed event. This is not replicated here. If someone is listening, they may replicate the InputPressed event to the server.
        InvokeReplicatedEvent(EAbilityGenericReplicatedEvent::InputPressed, Spec.Handle, OriginalPredictionKey);
    }
}
Referenced by ProcessAbilityInput().
AbilitySpecInputReleased()
void UAbilitySystemComponentBase::AbilitySpecInputReleased (FGameplayAbilitySpec & Spec) override protected virtual
Handles when an ability spec input is released.
Parameters
Spec The ability spec that had its input released.
Definition at line 210 of file AbilitySystemComponentBase.cpp.
{
    Super::AbilitySpecInputReleased(Spec);
    // We don't support UGameplayAbility::bReplicateInputDirectly.
    // Use replicated events instead so that the WaitInputRelease ability task works.
    if (Spec.IsActive())
    {
        FPredictionKey OriginalPredictionKey;
        if (const UGameplayAbility* Instance = Spec.GetPrimaryInstance())
        {
            OriginalPredictionKey = Instance->GetCurrentActivationInfo().GetActivationPredictionKey();
        }
        // Invoke the InputReleased event. This is not replicated here. If someone is listening, they may replicate the InputReleased event to the server.
        InvokeReplicatedEvent(EAbilityGenericReplicatedEvent::InputReleased, Spec.Handle, OriginalPredictionKey);
    }
}
Referenced by ProcessAbilityInput().
ClearAbilityInput()
void UAbilitySystemComponentBase::ClearAbilityInput ()
Clears all ability input.
Definition at line 164 of file AbilitySystemComponentBase.cpp.
{
    InputPressedSpecHandles.Reset();
    InputReleasedSpecHandles.Reset();
    InputHeldSpecHandles.Reset();
}
References InputHeldSpecHandles, InputPressedSpecHandles, and InputReleasedSpecHandles.
Referenced by ProcessAbilityInput().
GetLifetimeReplicatedProps()
void UAbilitySystemComponentBase::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override virtual
Definition at line 14 of file AbilitySystemComponentBase.cpp.
{
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
}
InitAbilitiesOnNewActorInfo()
void UAbilitySystemComponentBase::InitAbilitiesOnNewActorInfo () protected
Initializes abilities when a new actor info is set.
Definition at line 171 of file AbilitySystemComponentBase.cpp.
{
    if ([[maybe_unused]] const FGameplayAbilityActorInfo* ActorInfo = AbilityActorInfo.Get())
    {
        TryActivateAbilitiesOnSpawn();
    }
}
References TryActivateAbilitiesOnSpawn().
Referenced by InitAbilityActorInfo().
InitAbilityActorInfo()
void UAbilitySystemComponentBase::InitAbilityActorInfo (AActor * InOwnerActor, AActor * InAvatarActor) override virtual
Initialized the Abilities' ActorInfo - the structure that holds information about who we are acting on and who controls us. OwnerActor is the actor that logically owns this component. AvatarActor is what physical actor in the world we are acting on. Usually a Pawn but it could be a Tower, Building, Turret, etc, may be the same as Owner
Definition at line 19 of file AbilitySystemComponentBase.cpp.
{
    if (!IsValid(InOwnerActor))
    {
        return;
    }
    const FGameplayAbilityActorInfo* ActorInfo = AbilityActorInfo.Get();
    if (!ActorInfo)
    {
        return;
    }
    // Check if we have a new pawn avatar
    const bool bHasNewAvatar = Cast<APawn>(InAvatarActor) && (InAvatarActor != ActorInfo->AvatarActor);
    Super::InitAbilityActorInfo(InOwnerActor, InAvatarActor);
    // If we get a new pawn as avatar actor, initialize new actor info
    if (bHasNewAvatar)
    {
        InitAbilitiesOnNewActorInfo();
    }
}
References InitAbilitiesOnNewActorInfo().
NotifyAbilityEnded()
void UAbilitySystemComponentBase::NotifyAbilityEnded (FGameplayAbilitySpecHandle Handle, UGameplayAbility * Ability, bool bWasCancelled) override virtual
Called from the ability to let the component know it is ended
Definition at line 43 of file AbilitySystemComponentBase.cpp.
{
    Super::NotifyAbilityEnded(Handle, Ability, bWasCancelled);
}
ProcessAbilityInput()
void UAbilitySystemComponentBase::ProcessAbilityInput (float DeltaTime, bool bGamePaused)
Processes ability input.
Parameters
DeltaTime The time since the last frame.
bGamePaused Whether the game is paused.
Definition at line 78 of file AbilitySystemComponentBase.cpp.
{
    // Check if abilities input activation is blocked
    if (HasMatchingGameplayTag(AbilitySystemCoreTags::TAG_Gameplay_AbilitiesBlocked))
    {
        ClearAbilityInput();
        return;
    }
    static TArray<FGameplayAbilitySpecHandle> AbilitiesToActivate;
    AbilitiesToActivate.Reset();
    // Process all abilities that activate when the input is held.
    for (const FGameplayAbilitySpecHandle& SpecHandle : InputHeldSpecHandles)
    {
        if (const FGameplayAbilitySpec* AbilitySpec = FindAbilitySpecFromHandle(SpecHandle))
        {
            if (AbilitySpec->Ability && !AbilitySpec->IsActive())
            {
                const UGameplayAbilityBase* BaseAbilityCDO = Cast<UGameplayAbilityBase>(AbilitySpec->Ability);
                if (BaseAbilityCDO && BaseAbilityCDO->GetActivationPolicy() == EAbilityActivationPolicy::WhileInputActive)
                {
                    AbilitiesToActivate.AddUnique(AbilitySpec->Handle);
                }
            }
        }
    }
    // Process all abilities that had their input pressed this frame.
    for (const FGameplayAbilitySpecHandle& SpecHandle : InputPressedSpecHandles)
    {
        if (FGameplayAbilitySpec* AbilitySpec = FindAbilitySpecFromHandle(SpecHandle))
        {
            if (AbilitySpec->Ability)
            {
                AbilitySpec->InputPressed = true;
                if (AbilitySpec->IsActive())
                {
                    // Ability is active so pass along the input event.
                    AbilitySpecInputPressed(*AbilitySpec);
                }
                else
                {
                    const UGameplayAbilityBase* BaseAbilityCDO = Cast<UGameplayAbilityBase>(AbilitySpec->Ability);
                    if (BaseAbilityCDO && BaseAbilityCDO->GetActivationPolicy() == EAbilityActivationPolicy::OnInputTriggered)
                    {
                        AbilitiesToActivate.AddUnique(AbilitySpec->Handle);
                    }
                }
            }
        }
    }
    // Try to activate all the abilities that are from presses and holds.
    // We do it all at once so that held inputs don't activate the ability
    // and then also send a input event to the ability because of the press.
    for (const FGameplayAbilitySpecHandle& AbilitySpecHandle : AbilitiesToActivate)
    {
        TryActivateAbility(AbilitySpecHandle);
    }
    // Process all abilities that had their input released this frame.
    for (const FGameplayAbilitySpecHandle& SpecHandle : InputReleasedSpecHandles)
    {
        if (FGameplayAbilitySpec* AbilitySpec = FindAbilitySpecFromHandle(SpecHandle))
        {
            if (AbilitySpec->Ability)
            {
                AbilitySpec->InputPressed = false;
                if (AbilitySpec->IsActive())
                {
                    // Ability is active so pass along the input event.
                    AbilitySpecInputReleased(*AbilitySpec);
                }
            }
        }
    }
    // Clear the cached ability handles.
    InputPressedSpecHandles.Reset();
    InputReleasedSpecHandles.Reset();
}
References AbilitySpecInputPressed(), AbilitySpecInputReleased(), ClearAbilityInput(), UGameplayAbilityBase::GetActivationPolicy(), InputHeldSpecHandles, InputPressedSpecHandles, and InputReleasedSpecHandles.
TryActivateAbilitiesOnSpawn()
void UAbilitySystemComponentBase::TryActivateAbilitiesOnSpawn () protected
Tries to activate abilities on spawn. Applicable if the activation policy of the ability is EAbilityActivationPolicy::OnSpawn
Definition at line 179 of file AbilitySystemComponentBase.cpp.
{
    // Stop from removing ability from the ability system to iterate through the abilities
    ABILITYLIST_SCOPE_LOCK();
    for (const FGameplayAbilitySpec& AbilitySpec : ActivatableAbilities.Items)
    {
        const UGameplayAbilityBase* Ability = CastChecked<UGameplayAbilityBase>(AbilitySpec.Ability);
        Ability->TryActivateAbilityOnSpawn(AbilityActorInfo.Get(), AbilitySpec);
    }
}
References UGameplayAbilityBase::TryActivateAbilityOnSpawn().
Referenced by InitAbilitiesOnNewActorInfo().
Friends And Related Symbol Documentation
UGameplayAbilityBase
friend class UGameplayAbilityBase friend
Definition at line 21 of file AbilitySystemComponentBase.h.
Member Data Documentation
InputHeldSpecHandles
TArray<FGameplayAbilitySpecHandle> UAbilitySystemComponentBase::InputHeldSpecHandles protected
Handles to abilities that have their input held.
Definition at line 87 of file AbilitySystemComponentBase.h.
Referenced by AbilityInputTagPressed(), AbilityInputTagReleased(), ClearAbilityInput(), and ProcessAbilityInput().
InputPressedSpecHandles
TArray<FGameplayAbilitySpecHandle> UAbilitySystemComponentBase::InputPressedSpecHandles protected
Handles to abilities that had their input pressed this frame.
Definition at line 81 of file AbilitySystemComponentBase.h.
Referenced by AbilityInputTagPressed(), ClearAbilityInput(), and ProcessAbilityInput().
InputReleasedSpecHandles
TArray<FGameplayAbilitySpecHandle> UAbilitySystemComponentBase::InputReleasedSpecHandles protected
Handles to abilities that had their input released this frame.
Definition at line 84 of file AbilitySystemComponentBase.h.
Referenced by AbilityInputTagReleased(), ClearAbilityInput(), and ProcessAbilityInput().
The documentation for this class was generated from the following files:
Source/AbilitySystemCore/Public/Components/AbilitySystemComponentBase.h
Source/AbilitySystemCore/Private/Components/AbilitySystemComponentBase.cpp