GameplayCore Plugin: UItemDefinition Class Reference
UItemDefinition Class Reference
Data asset definition of an item that can be given/owned by a character.
#include <ItemDefinition.h>
Public Member Functions
UItemDefinition (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
virtual void PostLoad () override
const UItemFragment * FindFragmentByClass (TSubclassOf< UItemFragment > FragmentClass) const
bool HasFragmentByClass (TSubclassOf< UItemFragment > FragmentClass) const
template<typename T>
const T * FindFragmentByClass () const
virtual bool CanBeGiven (UInventorySystemComponent *InventorySystemComponent, FGameplayTag &OutFailureReason)
bool K2_CanBeGiven (UInventorySystemComponent *InventorySystemComponent, FGameplayTag &OutFailureReason)
Public Attributes
FText DisplayName
FText Description
TArray< TObjectPtr< UItemFragment > > Fragments
Detailed Description
Data asset definition of an item that can be given/owned by a character.
See also
UObject
Represents a template for items in the inventory system. Contains basic item information like name and description, and can be extended with fragments for additional functionality. This is an abstract class that should be inherited to create specific item types.
Definition at line 23 of file ItemDefinition.h.
Constructor & Destructor Documentation
UItemDefinition()
UItemDefinition::UItemDefinition (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get())
Definition at line 13 of file ItemDefinition.cpp.
    : Super(ObjectInitializer.Get())
{
}
Member Function Documentation
CanBeGiven()
bool UItemDefinition::CanBeGiven (UInventorySystemComponent * InventorySystemComponent, FGameplayTag & OutFailureReason) virtual
Checks if this item can be given to the specified inventory
Parameters
InventorySystemComponent The target inventory component
OutFailureReason
Returns
True if the item can be given, false otherwise
See also
UInventorySystemComponent
Definition at line 128 of file ItemDefinition.cpp.
{
    return K2_CanBeGiven(InventorySystemComponent, OutFailureReason);
}
References K2_CanBeGiven().
Referenced by FInventoryList::CanAdd().
FindFragmentByClass() [1/2]
template<typename T> const T * UItemDefinition::FindFragmentByClass () const inline
Template version of FindFragmentByClass for convenient type-safe fragment access
Template Parameters
T The specific fragment class type to find
Returns
Typed pointer to the found fragment, or nullptr if not found
See also
FindFragmentByClass
Definition at line 61 of file ItemDefinition.h.
{ return Cast<T>(FindFragmentByClass(T::StaticClass())); }
References FindFragmentByClass().
Referenced by FindFragmentByClass(), and HasFragmentByClass().
FindFragmentByClass() [2/2]
const UItemFragment * UItemDefinition::FindFragmentByClass (TSubclassOf< UItemFragment > FragmentClass) const
Searches for a specific fragment type in this item definition
Parameters
FragmentClass The class type of fragment to find
Returns
The found fragment instance, or nullptr if not found
See also
UItemFragment
Definition at line 106 of file ItemDefinition.cpp.
{
    if (IsValid(FragmentClass))
    {
        for (const UItemFragment* Fragment : Fragments)
        {
            if (IsValid(Fragment) && Fragment->IsA(FragmentClass))
            {
                return Fragment;
            }
        }
    }
    return nullptr;
}
References Fragments.
Referenced by FInventoryList::Add(), and FInventoryList::CanAdd().
HasFragmentByClass()
bool UItemDefinition::HasFragmentByClass (TSubclassOf< UItemFragment > FragmentClass) const
Checks if this item definition contains a specific fragment type
Parameters
FragmentClass The class type of fragment to check
Returns
True if the fragment exists, false otherwise
See also
UItemFragment
Definition at line 122 of file ItemDefinition.cpp.
{
    const bool bFound = FindFragmentByClass(FragmentClass) != nullptr;
    return bFound;
}
References FindFragmentByClass().
K2_CanBeGiven()
bool UItemDefinition::K2_CanBeGiven (UInventorySystemComponent * InventorySystemComponent, FGameplayTag & OutFailureReason)
Blueprint-accessible version of CanBeGiven
Parameters
InventorySystemComponent The target inventory component
OutFailureReason
Returns
True if the item can be given, false otherwise
See also
CanBeGiven
References K2_CanBeGiven().
Referenced by CanBeGiven(), and K2_CanBeGiven().
PostLoad()
void UItemDefinition::PostLoad () override virtual
Definition at line 18 of file ItemDefinition.cpp.
{
    UObject::PostLoad();
#if WITH_EDITORONLY_DATA
    PreviousFragments = Fragments;
#endif
}
Member Data Documentation
Description
FText UItemDefinition::Description
Detailed description of the item shown in the UI
Definition at line 88 of file ItemDefinition.h.
DisplayName
FText UItemDefinition::DisplayName
The display name of the item shown in the UI
Definition at line 84 of file ItemDefinition.h.
Fragments
TArray<TObjectPtr<UItemFragment> > UItemDefinition::Fragments
Collection of fragments that define the item's behavior and properties
Definition at line 92 of file ItemDefinition.h.
Referenced by FindFragmentByClass().
The documentation for this class was generated from the following files:
Source/InventorySystemCore/Public/Definitions/ItemDefinition.h
Source/InventorySystemCore/Private/Definitions/ItemDefinition.cpp