GameplayCore Plugin: UAbilitySet Class Reference
UAbilitySet Class Reference
#include <AbilitySet.h>
Public Member Functions
UAbilitySet (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
void GiveToAbilitySystem (UAbilitySystemComponent *AbilitySystemComp, FAbilitySetHandles *Handles, UObject *SourceObject=nullptr) const
Protected Attributes
TArray< FAbilitySet_GameplayAbility > GameplayAbilities
TArray< FAbilitySet_GameplayEffect > GameplayEffects
TArray< TSubclassOf< UAttributeSet > > AttributeSets
Detailed Description
UAbilitySet
Non-mutable data asset used to grant gameplay abilities, gameplay effects and attributes.
Definition at line 21 of file AbilitySet.h.
Constructor & Destructor Documentation
UAbilitySet()
UAbilitySet::UAbilitySet (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get())
Definition at line 12 of file AbilitySet.cpp.
                                                                    : Super(ObjectInitializer.Get())
{
}
Member Function Documentation
GiveToAbilitySystem()
void UAbilitySet::GiveToAbilitySystem (UAbilitySystemComponent * AbilitySystemComp, FAbilitySetHandles * Handles, UObject * SourceObject = nullptr) const
Grants the ability set to the specified ability system component. The returned handles can be used later to take away anything that was granted.
Definition at line 16 of file AbilitySet.cpp.
{
    check(AbilitySystemComp);
    if (!AbilitySystemComp->IsOwnerActorAuthoritative()) UE_LOG(LogAbilitySystem, Error, TEXT("Must be authoritive to give or take ability sets"));
    // Grant the attribut sets
    for (int Index = 0; Index < AttributeSets.Num(); ++Index)
    {
        const TSubclassOf<UAttributeSet>& AttributeSetClass = AttributeSets[Index];
        UE_CLOG(!IsValid(AttributeSetClass), LogAbilitySystem, Error, TEXT("Attributes[%d] on ability set [%s] is not valid"), Index, *GetNameSafe(this));
        UAttributeSet* AttributeSet = NewObject<UAttributeSet>(AbilitySystemComp, AttributeSetClass);
        AbilitySystemComp->AddAttributeSetSubobject(AttributeSet);
        if (Handles)
        {
            Handles->AddAttributeSet(AttributeSet);
        }
    }
    // Grant the gameplay abilities
    for (int Index = 0; Index < GameplayAbilities.Num(); ++Index)
    {
        const FAbilitySet_GameplayAbility& GameplayAbilitySet = GameplayAbilities[Index];
        UE_CLOG(!IsValid(GameplayAbilitySet.Ability), LogAbilitySystem, Error, TEXT("Attributes[%d] on ability set [%s] is not valid"), Index, *GetNameSafe(this));
        UGameplayAbilityBase* AbilityCDO = GameplayAbilitySet.Ability->GetDefaultObject<UGameplayAbilityBase>();
        FGameplayAbilitySpec AbilitySpec(AbilityCDO, GameplayAbilitySet.AbilityLevel);
        AbilitySpec.SourceObject = SourceObject;
        AbilitySpec.GetDynamicSpecSourceTags().AddTag(GameplayAbilitySet.InputTag);
        const FGameplayAbilitySpecHandle AbilitySpecHandle = AbilitySystemComp->GiveAbility(AbilitySpec);
        if (Handles)
        {
            Handles->AddAbilitySpecHandle(AbilitySpecHandle);
        }
    }
    // Grant the gameplay effects.
    for (int32 Index = 0; Index < GameplayEffects.Num(); ++Index)
    {
        const FAbilitySet_GameplayEffect& GameplayEffectSet = GameplayEffects[Index];
        UE_CLOG(!IsValid(GameplayEffectSet.GameplayEffect), LogAbilitySystem, Error, TEXT("Attributes[%d] on ability set [%s] is not valid"), Index, *GetNameSafe(this));
        const UGameplayEffect* GameplayEffect = GameplayEffectSet.GameplayEffect->GetDefaultObject<UGameplayEffect>();
        const FActiveGameplayEffectHandle GameplayEffectHandle = AbilitySystemComp->ApplyGameplayEffectToSelf(GameplayEffect, GameplayEffectSet.EffectLevel, AbilitySystemComp->MakeEffectContext());
        if (Handles)
        {
            Handles->AddGameplayEffectHandle(GameplayEffectHandle);
        }
    }
}
References FAbilitySetHandles::AddAbilitySpecHandle(), FAbilitySetHandles::AddAttributeSet(), FAbilitySetHandles::AddGameplayEffectHandle(), AttributeSets, GameplayAbilities, and GameplayEffects.
Member Data Documentation
AttributeSets
TArray<TSubclassOf<UAttributeSet> > UAbilitySet::AttributeSets protected
Attribute sets to grant when this ability set is granted.
Definition at line 45 of file AbilitySet.h.
Referenced by GiveToAbilitySystem().
GameplayAbilities
TArray<FAbilitySet_GameplayAbility> UAbilitySet::GameplayAbilities protected
Gameplay abilities to grant when this ability set is given.
Definition at line 37 of file AbilitySet.h.
Referenced by GiveToAbilitySystem().
GameplayEffects
TArray<FAbilitySet_GameplayEffect> UAbilitySet::GameplayEffects protected
Gameplay effects to grant when this ability set is granted.
Definition at line 41 of file AbilitySet.h.
Referenced by GiveToAbilitySystem().
The documentation for this class was generated from the following files:
Source/AbilitySystemCore/Public/Data/AbilitySet.h
Source/AbilitySystemCore/Private/Data/AbilitySet.cpp