GameplayCore Plugin: UGameplayAbilityBase Class Reference
UGameplayAbilityBase Class Reference
#include <GameplayAbilityBase.h>
Public Member Functions
UGameplayAbilityBase (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
EAbilityActivationPolicy GetActivationPolicy () const
Protected Member Functions
virtual void OnAvatarSet (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
virtual void OnGiveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
virtual void OnRemoveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
virtual void PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate *OnGameplayAbilityEndedDelegate, const FGameplayEventData *TriggerEventData) override
virtual void ActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, const FGameplayEventData *TriggerEventData) override
virtual bool CanActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayTagContainer *SourceTags, const FGameplayTagContainer *TargetTags, FGameplayTagContainer *OptionalRelevantTags) const override
virtual bool DoesAbilitySatisfyTagRequirements (const UAbilitySystemComponent &AbilitySystemComponent, const FGameplayTagContainer *SourceTags, const FGameplayTagContainer *TargetTags, FGameplayTagContainer *OptionalRelevantTags) const override
virtual void EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override
void K2_OnAbilityGiven ()
void K2_OnAbilityRemoved ()
void TryActivateAbilityOnSpawn (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) const
Protected Attributes
EAbilityActivationPolicy ActivationPolicy
Friends
class UAbilitySystemComponentBase
Detailed Description
UGameplayAbilityBase
Abilities define custom game logic that can be activated by players or by external game logic.
Definition at line 17 of file GameplayAbilityBase.h.
Constructor & Destructor Documentation
UGameplayAbilityBase()
UGameplayAbilityBase::UGameplayAbilityBase (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get()) explicit
Definition at line 8 of file GameplayAbilityBase.cpp.
{
    ReplicationPolicy = EGameplayAbilityReplicationPolicy::ReplicateNo;
    InstancingPolicy = EGameplayAbilityInstancingPolicy::InstancedPerActor;
    NetExecutionPolicy = EGameplayAbilityNetExecutionPolicy::LocalPredicted;
    NetSecurityPolicy = EGameplayAbilityNetSecurityPolicy::ClientOrServer;
    ActivationPolicy = EAbilityActivationPolicy::OnInputTriggered;
}
Member Function Documentation
ActivateAbility()
void UGameplayAbilityBase::ActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, const FGameplayEventData * TriggerEventData) override protected virtual
Definition at line 53 of file GameplayAbilityBase.cpp.
{
    Super::ActivateAbility(Handle, ActorInfo, ActivationInfo, TriggerEventData);
}
CanActivateAbility()
bool UGameplayAbilityBase::CanActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayTagContainer * SourceTags, const FGameplayTagContainer * TargetTags, FGameplayTagContainer * OptionalRelevantTags) const nodiscard override protected virtual
Definition at line 62 of file GameplayAbilityBase.cpp.
{
    return Super::CanActivateAbility(Handle, ActorInfo, SourceTags, TargetTags, OptionalRelevantTags);
}
DoesAbilitySatisfyTagRequirements()
bool UGameplayAbilityBase::DoesAbilitySatisfyTagRequirements (const UAbilitySystemComponent & AbilitySystemComponent, const FGameplayTagContainer * SourceTags, const FGameplayTagContainer * TargetTags, FGameplayTagContainer * OptionalRelevantTags) const override protected virtual
Definition at line 72 of file GameplayAbilityBase.cpp.
{
    bool bBlocked = false;
    bool bMissing = false;
    UAbilitySystemGlobalsBase& AbilitySystemGlobals = UAbilitySystemGlobalsBase::Get();
    const FGameplayTag& BlockedTag = AbilitySystemGlobals.ActivateFailTagsBlockedTag;
    const FGameplayTag& MissingTag = AbilitySystemGlobals.ActivateFailTagsMissingTag;
    // Check if any of this ability's tags are currently blocked
    if (AbilitySystemComponent.AreAbilityTagsBlocked(GetAssetTags()))
    {
        bBlocked = true;
    }
    // Check to see the required/blocked tags for this ability
    if (ActivationBlockedTags.Num() || ActivationRequiredTags.Num())
    {
        static FGameplayTagContainer AbilitySystemComponentTags;
        AbilitySystemComponentTags.Reset();
        AbilitySystemComponent.GetOwnedGameplayTags(AbilitySystemComponentTags);
        AbilitySystemComponent.GetBlockedAbilityTags(AbilitySystemComponentTags);
        if (AbilitySystemComponentTags.HasAny(ActivationBlockedTags))
        {
            bBlocked = true;
        }
        if (!AbilitySystemComponentTags.HasAll(ActivationRequiredTags))
        {
            bMissing = true;
        }
    }
    // Check source tags
    if (SourceTags != nullptr)
    {
        if (SourceBlockedTags.Num() || SourceRequiredTags.Num())
        {
            if (SourceTags->HasAny(SourceBlockedTags))
            {
                bBlocked = true;
            }
            if (!SourceTags->HasAll(SourceRequiredTags))
            {
                bMissing = true;
            }
        }
    }
    // Check target tags
    if (TargetTags != nullptr)
    {
        if (TargetBlockedTags.Num() || TargetRequiredTags.Num())
        {
            if (TargetTags->HasAny(TargetBlockedTags))
            {
                bBlocked = true;
            }
            if (!TargetTags->HasAll(TargetRequiredTags))
            {
                bMissing = true;
            }
        }
    }
    // We succeeded if there were no blocked tags and no missing required tags
    return !bBlocked && !bMissing;
}
EndAbility()
void UGameplayAbilityBase::EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override protected virtual
Definition at line 149 of file GameplayAbilityBase.cpp.
{
    Super::EndAbility(Handle, ActorInfo, ActivationInfo, bReplicateEndAbility, bWasCancelled);
}
GetActivationPolicy()
EAbilityActivationPolicy UGameplayAbilityBase::GetActivationPolicy () const inline
Gets the activation policy for this ability.
Returns
The activation policy.
Definition at line 31 of file GameplayAbilityBase.h.
{ return ActivationPolicy; }
References ActivationPolicy, and GetActivationPolicy().
Referenced by GetActivationPolicy(), and UAbilitySystemComponentBase::ProcessAbilityInput().
K2_OnAbilityGiven()
void UGameplayAbilityBase::K2_OnAbilityGiven () protected
Called when this ability is granted to the ability system component. Can be implemented in Blueprints.
References K2_OnAbilityGiven().
Referenced by K2_OnAbilityGiven().
K2_OnAbilityRemoved()
void UGameplayAbilityBase::K2_OnAbilityRemoved () protected
Called when this ability is removed from the ability system component. Can be implemented in Blueprints.
References K2_OnAbilityRemoved().
Referenced by K2_OnAbilityRemoved().
OnAvatarSet()
void UGameplayAbilityBase::OnAvatarSet (const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilitySpec & Spec) override protected virtual
Definition at line 18 of file GameplayAbilityBase.cpp.
{
    Super::OnAvatarSet(ActorInfo, Spec);
    // OnAvatarSet being called by Super::OnGiveAbility if it has a valid AvatarActor
    // try to activate the ability
    TryActivateAbilityOnSpawn(ActorInfo, Spec);
}
OnGiveAbility()
void UGameplayAbilityBase::OnGiveAbility (const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilitySpec & Spec) override protected virtual
Definition at line 27 of file GameplayAbilityBase.cpp.
{
    Super::OnGiveAbility(ActorInfo, Spec);
    // Call blueprint implementation after the ability is given
    K2_OnAbilityGiven();
}
OnRemoveAbility()
void UGameplayAbilityBase::OnRemoveAbility (const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilitySpec & Spec) override protected virtual
Definition at line 35 of file GameplayAbilityBase.cpp.
{
    // Call blueprint implementation before the ability is removed.
    K2_OnAbilityRemoved();
    Super::OnRemoveAbility(ActorInfo, Spec);
}
PreActivate()
void UGameplayAbilityBase::PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate * OnGameplayAbilityEndedDelegate, const FGameplayEventData * TriggerEventData) override protected virtual
Definition at line 43 of file GameplayAbilityBase.cpp.
{
    Super::PreActivate(Handle, ActorInfo, ActivationInfo, OnGameplayAbilityEndedDelegate, TriggerEventData);
}
TryActivateAbilityOnSpawn()
void UGameplayAbilityBase::TryActivateAbilityOnSpawn (const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilitySpec & Spec) const protected
Tries to activate the ability when it spawns.
Definition at line 159 of file GameplayAbilityBase.cpp.
{
    const bool bIsPredicting = (Spec.GetPrimaryInstance()->GetCurrentActivationInfo().ActivationMode == EGameplayAbilityActivationMode::Predicting);
    // Try to activate if activation policy is OnSpawn.
    if (ActorInfo && !Spec.IsActive() && !bIsPredicting && (ActivationPolicy == EAbilityActivationPolicy::OnSpawn))
    {
        UAbilitySystemComponent* AbilitySystemComp = ActorInfo->AbilitySystemComponent.Get();
        const AActor* AvatarActor = ActorInfo->AvatarActor.Get();
        if (IsValid(AbilitySystemComp) && IsValid(AvatarActor))
        {
            // Don't try to activate the ability if the avatar is being destroyed and no longer replicated
            if (!AvatarActor->GetTearOff() && AvatarActor->GetLifeSpan() <= 0.0f)
            {
                // Activate the ability only if we're on the authority
                const bool bIsLocalExecution = (NetExecutionPolicy == EGameplayAbilityNetExecutionPolicy::LocalPredicted) || (NetExecutionPolicy == EGameplayAbilityNetExecutionPolicy::LocalOnly);
                const bool bIsServerExecution = (NetExecutionPolicy == EGameplayAbilityNetExecutionPolicy::ServerOnly) || (NetExecutionPolicy == EGameplayAbilityNetExecutionPolicy::ServerInitiated);
                const bool bClientShouldActivate = ActorInfo->IsLocallyControlled() && bIsLocalExecution;
                const bool bServerShouldActivate = ActorInfo->IsNetAuthority() && bIsServerExecution;
                if (bClientShouldActivate || bServerShouldActivate)
                {
                    AbilitySystemComp->TryActivateAbility(Spec.Handle);
                }
            }
        }
    }
}
References ActivationPolicy.
Referenced by UAbilitySystemComponentBase::TryActivateAbilitiesOnSpawn().
Friends And Related Symbol Documentation
UAbilitySystemComponentBase
friend class UAbilitySystemComponentBase friend
Definition at line 21 of file GameplayAbilityBase.h.
Member Data Documentation
ActivationPolicy
EAbilityActivationPolicy UGameplayAbilityBase::ActivationPolicy protected
Defines how the ability is supposed to be activated.
Definition at line 75 of file GameplayAbilityBase.h.
Referenced by GetActivationPolicy(), and TryActivateAbilityOnSpawn().
The documentation for this class was generated from the following files:
Source/AbilitySystemCore/Public/Abilities/GameplayAbilityBase.h
Source/AbilitySystemCore/Private/Abilities/GameplayAbilityBase.cpp