GameplayCore Plugin: UItemInstance Class Reference
UItemInstance Class Reference
This class represents an instance of an item within the inventory system. It holds a reference to the item definition and provides functionalities related to item management. This class uses a component-based architecture to allow for flexible and efficient item instances. Each instance can have multiple components that add specific functionalities.
#include <ItemInstance.h>
Public Member Functions
UItemInstance (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
virtual bool IsSupportedForNetworking () const override
UInventorySystemComponent * GetInventorySystemComponent () const
APlayerController * GetOwningController () const
template<typename T>
const T * GetOwningController () const
TSubclassOf< UItemDefinition > GetDefinitionClass () const
UItemDefinition * GetDefinition () const
const UItemFragment * FindFragmentByClass (TSubclassOf< UItemFragment > FragmentClass) const
template<typename T>
const T * FindFragmentByClass () const
bool HasFragmentByClass (TSubclassOf< UItemFragment > FragmentClass) const
UItemComponent * AddComponent (TSubclassOf< UItemComponent > ComponentClass)
template<typename T>
T * AddComponent ()
const UItemComponent * FindComponentByClass (TSubclassOf< UItemComponent > ComponentClass) const
template<typename T>
const T * FindComponentByClass () const
Protected Member Functions
void SetDefinition (UItemDefinition *InDefinition)
Protected Attributes
TSubclassOf< UItemDefinition > DefinitionClass
TWeakObjectPtr< UItemDefinition > Definition
TArray< UItemComponent * > Components
APlayerController * OwningController
Friends
struct FInventoryList
Detailed Description
This class represents an instance of an item within the inventory system. It holds a reference to the item definition and provides functionalities related to item management. This class uses a component-based architecture to allow for flexible and efficient item instances. Each instance can have multiple components that add specific functionalities.
See also
UObject
Definition at line 24 of file ItemInstance.h.
Constructor & Destructor Documentation
UItemInstance()
UItemInstance::UItemInstance (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get()) explicit
Definition at line 9 of file ItemInstance.cpp.
    : Super(ObjectInitializer)
{
    OwningController = GetTypedOuter<APlayerController>();
}
Member Function Documentation
AddComponent() [1/2]
template<typename T> T * UItemInstance::AddComponent () inline
Try to find fragment of class FragmentClass in this item definition
Definition at line 97 of file ItemInstance.h.
{ return Cast<T>(AddComponent(T::StaticClass())); }
References AddComponent(), and AddComponent().
Referenced by AddComponent().
AddComponent() [2/2]
UItemComponent * UItemInstance::AddComponent (TSubclassOf< UItemComponent > ComponentClass)
Try to find fragment of class FragmentClass in this item definition
Parameters
ComponentClass Class of the ItemFragment to search
Definition at line 71 of file ItemInstance.cpp.
{
    if (UItemComponent* Component = NewObject<UItemComponent>(this, ComponentClass); IsValid(Component))
    {
        Components.Add(Component);
        return Component;
    }
    return nullptr;
}
References Components.
Referenced by AddComponent(), and UItemFragment_Consumable::OnInstanceCreated().
FindComponentByClass() [1/2]
template<typename T> const T * UItemInstance::FindComponentByClass () const inline
Try to find a component of type T attached to this item instance
Returns
The found component cast to type T, or nullptr if not found or cast fails
Definition at line 110 of file ItemInstance.h.
{ return Cast<T*>(FindComponentByClass(T::StaticClass())); }
References FindComponentByClass().
Referenced by FindComponentByClass().
FindComponentByClass() [2/2]
const UItemComponent * UItemInstance::FindComponentByClass (TSubclassOf< UItemComponent > ComponentClass) const
Try to find component of class ComponentClass of this item instance
Parameters
ComponentClass Class of the Item Instance's component to search
Definition at line 87 of file ItemInstance.cpp.
{
    if (IsValid(ComponentClass))
    {
        for (const UItemComponent* Component : Components)
        {
            if (IsValid(Component) && Component->IsA(ComponentClass))
            {
                return Component;
            }
        }
    }
    return nullptr;
}
References Components.
FindFragmentByClass() [1/2]
template<typename T> const T * UItemInstance::FindFragmentByClass () const inline
Try to find fragment of class FragmentClass in this item's definition
Definition at line 82 of file ItemInstance.h.
{ return Cast<T>(FindFragmentByClass(T::StaticClass())); }
References FindFragmentByClass().
Referenced by FindFragmentByClass().
FindFragmentByClass() [2/2]
const UItemFragment * UItemInstance::FindFragmentByClass (TSubclassOf< UItemFragment > FragmentClass) const
Try to find fragment of class FragmentClass in this item's definition
Parameters
FragmentClass Class of the ItemFragment to search
Definition at line 51 of file ItemInstance.cpp.
{
    if (Definition.IsValid() && IsValid(FragmentClass))
    {
        return Definition->FindFragmentByClass(FragmentClass);
    }
    return nullptr;
}
References Definition.
Referenced by UEquipmentSystemComponent::TryEquipItem(), UEquipmentSystemComponent::TryEquipItemOnSlot(), and UEquipmentSystemComponent::TrySwapSlots().
GetDefinition()
UItemDefinition * UItemInstance::GetDefinition () const
Gets the item definition associated with this instance, cached by the Inventory System Component.
Returns
The item definition default object.
Definition at line 46 of file ItemInstance.cpp.
{
    return Definition.Get();
}
References Definition.
GetDefinitionClass()
TSubclassOf< UItemDefinition > UItemInstance::GetDefinitionClass () const
Gets the item definition class associated with this instance.
Returns
The item definition class.
Definition at line 41 of file ItemInstance.cpp.
{
    return DefinitionClass;
}
References DefinitionClass.
GetInventorySystemComponent()
UInventorySystemComponent * UItemInstance::GetInventorySystemComponent () const
Gets the inventory system component that owns this item instance
Returns
The owning inventory system component
Definition at line 22 of file ItemInstance.cpp.
{
    if (!IsValid(OwningController))
    {
        return nullptr;
    }
    if (UInventorySystemComponent* InventorySystemComp = OwningController->GetComponentByClass<UInventorySystemComponent>(); IsValid(InventorySystemComp))
    {
        return InventorySystemComp;
    }
    return nullptr;
}
References OwningController.
GetLifetimeReplicatedProps()
void UItemInstance::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override virtual
Definition at line 15 of file ItemInstance.cpp.
{
    UObject::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(ThisClass, DefinitionClass);
}
GetOwningController() [1/2]
APlayerController * UItemInstance::GetOwningController () const
Gets the player controller that owns this item instance
Returns
The owning player controller
Definition at line 36 of file ItemInstance.cpp.
{
    return OwningController;
}
References OwningController.
GetOwningController() [2/2]
template<typename T> const T * UItemInstance::GetOwningController () const inline
Gets the owning controller cast to the specified type
Returns
The owning controller cast to type T, or nullptr if cast fails
Definition at line 56 of file ItemInstance.h.
{ return Cast<T>(GetOwningController(T::StaticClass())); }
References GetOwningController().
Referenced by GetOwningController().
HasFragmentByClass()
bool UItemInstance::HasFragmentByClass (TSubclassOf< UItemFragment > FragmentClass) const
Definition at line 61 of file ItemInstance.cpp.
{
    if (Definition.IsValid() && IsValid(FragmentClass))
    {
        return Definition->HasFragmentByClass(FragmentClass);
    }
    return false;
}
IsSupportedForNetworking()
virtual bool UItemInstance::IsSupportedForNetworking () const inline override virtual
Definition at line 35 of file ItemInstance.h.
{ return true; }
SetDefinition()
void UItemInstance::SetDefinition (UItemDefinition * InDefinition) protected
Sets the item definition class for this instance.
Parameters
InDefinition - The item definition to set.
Definition at line 81 of file ItemInstance.cpp.
{
    Definition = InDefinition;
    DefinitionClass = InDefinition->GetClass();
}
References Definition, and DefinitionClass.
Friends And Related Symbol Documentation
FInventoryList
friend struct FInventoryList friend
Definition at line 28 of file ItemInstance.h.
Member Data Documentation
Components
TArray<UItemComponent*> UItemInstance::Components protected
Components attached to this item instance providing additional functionality
Definition at line 131 of file ItemInstance.h.
Referenced by AddComponent(), and FindComponentByClass().
Definition
TWeakObjectPtr<UItemDefinition> UItemInstance::Definition protected
The Item Definition default object, cached by the local InventorySystemComponent cache
Definition at line 127 of file ItemInstance.h.
Referenced by FindFragmentByClass(), GetDefinition(), and SetDefinition().
DefinitionClass
TSubclassOf<UItemDefinition> UItemInstance::DefinitionClass protected
The item definition that this instance is based on. Only replicate the class.
Definition at line 123 of file ItemInstance.h.
Referenced by GetDefinitionClass(), and SetDefinition().
OwningController
APlayerController* UItemInstance::OwningController mutable protected
Cached pointer to the player controller that owns this item instance
Definition at line 135 of file ItemInstance.h.
Referenced by GetInventorySystemComponent(), and GetOwningController().
The documentation for this class was generated from the following files:
Source/InventorySystemCore/Public/Instances/ItemInstance.h
Source/InventorySystemCore/Private/Instances/ItemInstance.cpp