GameplayCore Plugin: UGameInitStateSubsystem Class Reference
UGameInitStateSubsystem Class Reference
#include <GameInitStateSubsystem.h>
Public Member Functions
virtual void Initialize (FSubsystemCollectionBase &Collection) override
virtual void Deinitialize () override
void RegisterFeatureImplementer (AActor *Actor, FName FeatureName, UObject *Implementer, const TArray< FGameplayTag > &InitStateTags={})
void RemoveActorFeatureData (AActor *Actor)
void RemoveFeatureImplementer (AActor *Actor, UObject *Implementer)
void SetFeatureInitStatTags (AActor *Actor, FName FeatureName, TArray< FGameplayTag > InitStateTags)
bool HasFeatureReachedInitState (AActor *Actor, FName FeatureName, FGameplayTag StateTag)
FGameplayTag GetInitStateForFeature (AActor *Actor, FName FeatureName) const
TArray< FGameplayTag > GetAllInitStatesForFeature (AActor *Actor, FName FeatureName) const
FDelegateHandle RegisterAndCallForActorInitState (AActor *Actor, FName FeatureName, FGameplayTag RequiredState, FActorInitStateChangedDelegate Delegate, bool bCallImmediately=true)
bool UnregisterActorInitStateDelegate (AActor *Actor, FDelegateHandle &Handle)
bool RegisterAndCallForActorInitState (AActor *Actor, FName FeatureName, FGameplayTag RequiredState, FActorInitStateChangedBPDelegate Delegate, bool bCallImmediately=true)
bool UnregisterActorInitStateDelegate (AActor *Actor, FActorInitStateChangedBPDelegate DelegateToRemove)
Static Public Member Functions
static UGameInitStateSubsystem * GetForActor (const AActor *Actor, bool bOnlyGameWorlds=true)
static bool IsInitStateCurrentOrLate (const FActorFeatureState &FeatureState, FGameplayTag RelativeState)
Detailed Description
This subsystem is highly based on ModularGameplay plugin's GameFrameworkComponentManager from Epic. To better handle initialization.
The init state system can be used by components to coordinate their initialization using game-specific states specified as gameplay tags IGameInitStateInterface provides a simple implementation that can be inherited by components
Definition at line 22 of file GameInitStateSubsystem.h.
Member Function Documentation
Deinitialize()
void UGameInitStateSubsystem::Deinitialize () override virtual
Definition at line 14 of file GameInitStateSubsystem.cpp.
{
    Super::Deinitialize();
#if WITH_EDITORONLY_DATA
    FCoreUObjectDelegates::GetPostGarbageCollect().RemoveAll(this);
#endif
}
GetAllInitStatesForFeature()
TArray< FGameplayTag > UGameInitStateSubsystem::GetAllInitStatesForFeature (AActor * Actor, FName FeatureName) const
Returns the earliest state found for the given feature
Definition at line 137 of file GameInitStateSubsystem.cpp.
{
    if (const FActorFeatureState* FoundState = FindFeatureStateStruct(ActorFeatureMap.Find(FObjectKey(Actor)), FeatureName, FGameplayTag()))
    {
        return FoundState->States;
    }
    return {};
}
GetForActor()
UGameInitStateSubsystem * UGameInitStateSubsystem::GetForActor (const AActor * Actor, bool bOnlyGameWorlds = true) static
Utility to get this manager from an actor, will return null if actor is null or not in a world
Definition at line 23 of file GameInitStateSubsystem.cpp.
{
    if (Actor)
    {
        if (const UWorld* ActorWorld = Actor->GetWorld())
        {
            if (bOnlyGameWorlds && (!ActorWorld->IsGameWorld() || ActorWorld->IsPreviewWorld()))
            {
                return nullptr;
            }
            return UGameInstance::GetSubsystem<UGameInitStateSubsystem>(ActorWorld->GetGameInstance());
        }
    }
    return nullptr;
}
Referenced by IGameInitStateInterface::BindOnActorInitStateChanged(), IGameInitStateInterface::GetAllInitStatesFor(), IGameInitStateInterface::GetCurrentInitStateFor(), IGameInitStateInterface::GetGameInitStateSubsystem(), IGameInitStateInterface::HasReachedInitState(), IGameInitStateInterface::RegisterAndCallForActorInitState(), IGameInitStateInterface::RegisterInitStateFeature(), IGameInitStateInterface::UnregisterInitStateDelegate(), and IGameInitStateInterface::UnregisterInitStateFeature().
GetInitStateForFeature()
FGameplayTag UGameInitStateSubsystem::GetInitStateForFeature (AActor * Actor, FName FeatureName) const
Returns the earliest state found for the given feature
Definition at line 127 of file GameInitStateSubsystem.cpp.
{
    if (const FActorFeatureState* FoundState = FindFeatureStateStruct(ActorFeatureMap.Find(FObjectKey(Actor)), FeatureName, FGameplayTag()))
    {
        return FoundState->CurrentState;
    }
    return FGameplayTag();
}
References FActorFeatureState::CurrentState.
HasFeatureReachedInitState()
bool UGameInitStateSubsystem::HasFeatureReachedInitState (AActor * Actor, FName FeatureName, FGameplayTag StateTag)
Returns true if feature has reached query state or later
Definition at line 120 of file GameInitStateSubsystem.cpp.
{
    FActorFeatureData* FeatureData = ActorFeatureMap.Find(Actor);
    const FActorFeatureState* FoundState = FeatureData->RegisteredStates.FindByPredicate([FeatureName](const FActorFeatureState& State) { return State.FeatureName == FeatureName; });
    return IsInitStateCurrentOrLate(*FoundState, StateTag);
}
References FActorFeatureState::FeatureName, IsInitStateCurrentOrLate(), and FActorFeatureData::RegisteredStates.
Initialize()
void UGameInitStateSubsystem::Initialize (FSubsystemCollectionBase & Collection) override virtual
Definition at line 7 of file GameInitStateSubsystem.cpp.
{
    Super::Initialize(Collection);
    CurrentStateChange = INDEX_NONE;
}
IsInitStateCurrentOrLate()
bool UGameInitStateSubsystem::IsInitStateCurrentOrLate (const FActorFeatureState & FeatureState, FGameplayTag RelativeState) static
Returns true if FeatureState comes after the second state (or is equal)
Definition at line 102 of file GameInitStateSubsystem.cpp.
{
    if (!FeatureState.IsValid())
    {
        return false;
    }
    if (FeatureState.CurrentState == RelativeState)
    {
        return true;
    }
    const int32 CurrentStateIndex = FeatureState.States.IndexOfByKey(FeatureState.CurrentState);
    const int32 RelateStateIndex = FeatureState.States.IndexOfByKey(RelativeState);
    return RelateStateIndex > CurrentStateIndex;
}
References FActorFeatureState::CurrentState.
Referenced by HasFeatureReachedInitState().
RegisterAndCallForActorInitState() [1/2]
bool UGameInitStateSubsystem::RegisterAndCallForActorInitState (AActor * Actor, FName FeatureName, FGameplayTag RequiredState, FActorInitStateChangedBPDelegate Delegate, bool bCallImmediately = true)
Registers blueprint delegate for feature state change notifications on a specific actor and may call it immediately
Parameters
Actor The actor to listen for state changes to, if you don't have a specific actor call the Class version instead
FeatureName If not empty, only listen to state changes for the specified feature
RequiredState If specified, only activate if the init state of the feature is equal to or later than this
Delegate Native delegate to call
bCallImmediately If true and the actor feature is already in the specified state, call delegate immediately after registering
Returns
true if delegate was registered
Definition at line 181 of file GameInitStateSubsystem.cpp.
{
    if (ensure(Actor && Delegate.IsBound()))
    {
        // We often register delegates before registering states
        FActorFeatureData& ActorStruct = FindOrAddActorData(Actor);
        const TSharedRef<FActorFeatureRegisteredDelegate> RegisteredDelegate = MakeShared<FActorFeatureRegisteredDelegate>(MoveTemp(Delegate), FeatureName, RequiredState);
        ActorStruct.RegisteredDelegates.Add(RegisteredDelegate);
        if (bCallImmediately)
        {
            // The shared ref keeps the delegate alive in case it gets unregistered
            CallDelegateForMatchingFeatures(Actor, *RegisteredDelegate);
        }
        return true;
    }
    return false;
}
References FActorFeatureData::RegisteredDelegates.
RegisterAndCallForActorInitState() [2/2]
FDelegateHandle UGameInitStateSubsystem::RegisterAndCallForActorInitState (AActor * Actor, FName FeatureName, FGameplayTag RequiredState, FActorInitStateChangedDelegate Delegate, bool bCallImmediately = true)
Registers native delegate for feature state change notifications on a specific actor and may call it immediately
Parameters
Actor The actor to listen for state changes to, if you don't have a specific actor call the Class version instead
FeatureName If not empty, only listen to state changes for the specified feature
RequiredState If specified, only activate if the init state of the feature is equal to or later than this
Delegate Native delegate to call
bCallImmediately If true and the actor feature is already in the specified state, call delegate immediately after registering
Returns
DelegateHandle used for later removal
Definition at line 146 of file GameInitStateSubsystem.cpp.
{
    if (ensure(Actor && Delegate.IsBound()))
    {
        // We often register delegates before registering states
        FActorFeatureData& ActorStruct = FindOrAddActorData(Actor);
        const TSharedRef<FActorFeatureRegisteredDelegate> RegisteredDelegate = MakeShared<FActorFeatureRegisteredDelegate>(MoveTemp(Delegate), FeatureName, RequiredState);
        ActorStruct.RegisteredDelegates.Add(RegisteredDelegate);
        if (bCallImmediately)
        {
            // The shared ref keeps the delegate alive in case it gets unregistered
            CallDelegateForMatchingFeatures(Actor, *RegisteredDelegate);
        }
        return RegisteredDelegate->DelegateHandle;
    }
    return FDelegateHandle();
}
References FActorFeatureData::RegisteredDelegates.
Referenced by IGameInitStateInterface::BindOnActorInitStateChanged(), and IGameInitStateInterface::RegisterAndCallForActorInitState().
RegisterFeatureImplementer()
void UGameInitStateSubsystem::RegisterFeatureImplementer (AActor * Actor, FName FeatureName, UObject * Implementer, const TArray< FGameplayTag > & InitStateTags = {})
Adds a new global actor feature state, either before or after an existing one. This will generally be called from game global or game feature initialization
Definition at line 41 of file GameInitStateSubsystem.cpp.
{
    ensure(Actor == nullptr || FeatureName.IsNone());
    auto& [ActorClass, RegisteredStates, RegisteredDelegates] = FindOrAddActorData(Actor);
    FActorFeatureState* FoundState = RegisteredStates.FindByPredicate([FeatureName](const FActorFeatureState& State) { return State.FeatureName == FeatureName; });
    if (!FoundState)
    {
        // We've not found a matching Feature State, create a new one.
        FoundState = &RegisteredStates.Emplace_GetRef(FeatureName);
    }
    FoundState->Implementer = Implementer;
    FoundState->States = InitStateTags;
}
References FActorFeatureState::FeatureName, and FActorFeatureState::Implementer.
Referenced by IGameInitStateInterface::RegisterInitStateFeature().
RemoveActorFeatureData()
void UGameInitStateSubsystem::RemoveActorFeatureData (AActor * Actor)
Removes an actor and all of it's state information
Definition at line 58 of file GameInitStateSubsystem.cpp.
{
    ActorFeatureMap.Remove(FObjectKey(Actor));
}
RemoveFeatureImplementer()
void UGameInitStateSubsystem::RemoveFeatureImplementer (AActor * Actor, UObject * Implementer)
Removes an implementing object and any feature states it implements
Definition at line 63 of file GameInitStateSubsystem.cpp.
{
    if (Actor == nullptr || Implementer == nullptr)
    {
        return;
    }
    TWeakObjectPtr WeakToRemove(Implementer);
    if (FActorFeatureData* FoundStruct = ActorFeatureMap.Find(FObjectKey(Actor)))
    {
        for (int32 i = FoundStruct->RegisteredStates.Num() - 1; i >= 0; i--)
        {
            // Clear if it matches or is stale
            const UObject* ResolvedObject = FoundStruct->RegisteredStates[i].Implementer.Get();
            if (ResolvedObject == Implementer || (!ResolvedObject && !FoundStruct->RegisteredStates[i].Implementer.IsExplicitlyNull()))
            {
                FoundStruct->RegisteredStates.RemoveAt(i);
            }
        }
    }
}
SetFeatureInitStatTags()
void UGameInitStateSubsystem::SetFeatureInitStatTags (AActor * Actor, FName FeatureName, TArray< FGameplayTag > InitStateTags)
Definition at line 86 of file GameInitStateSubsystem.cpp.
{
    ensure(Actor == nullptr || FeatureName.IsNone());
    FActorFeatureData& FeatureData = FindOrAddActorData(Actor);
    FActorFeatureState* FoundState = FeatureData.RegisteredStates.FindByPredicate([FeatureName](const FActorFeatureState& State) { return State.FeatureName == FeatureName; });
    if (FoundState)
    {
        FoundState->States = InitStateTags;
        FoundState->CurrentState = InitStateTags[0];
    }
    ProcessFeatureStateChange(Actor, FoundState);
}
UnregisterActorInitStateDelegate() [1/2]
bool UGameInitStateSubsystem::UnregisterActorInitStateDelegate (AActor * Actor, FActorInitStateChangedBPDelegate DelegateToRemove)
Removes a registered delegate bound to a specific actor
Definition at line 203 of file GameInitStateSubsystem.cpp.
{
    if (Actor && DelegateToRemove.IsBound())
    {
        if (FActorFeatureData* ActorStruct = ActorFeatureMap.Find(FObjectKey(Actor)))
        {
            return RemoveActorFeatureDelegateFromList(ActorStruct->RegisteredDelegates, DelegateToRemove);
        }
    }
    return false;
}
UnregisterActorInitStateDelegate() [2/2]
bool UGameInitStateSubsystem::UnregisterActorInitStateDelegate (AActor * Actor, FDelegateHandle & Handle)
Removes a registered delegate bound to a specific actor
Definition at line 168 of file GameInitStateSubsystem.cpp.
{
    if (Actor && Handle.IsValid())
    {
        if (FActorFeatureData* ActorStruct = ActorFeatureMap.Find(FObjectKey(Actor)))
        {
            return RemoveActorFeatureDelegateFromList(ActorStruct->RegisteredDelegates, Handle);
        }
    }
    return false;
}
The documentation for this class was generated from the following files:
Source/GameplayCore/Public/Components/GameInitStateSubsystem.h
Source/GameplayCore/Private/Components/GameInitStateSubsystem.cpp