GameplayCore Plugin: IGameInitStateInterface Class Reference
IGameInitStateInterface Class Reference
Public Member Functions
virtual AActor * GetOwningActor () const
UGameInitStateSubsystem * GetGameInitStateSubsystem () const
virtual FGameplayTag GetCurrentInitStateFor (FName &FeatureName) const
virtual bool HasReachedInitState (FName FeatureName, FGameplayTag DesiredState) const
virtual TArray< FGameplayTag > GetAllInitStatesFor (FName &FeatureName) const
virtual void CheckDefaultInitialization ()
virtual void OnActorInitStateChanged (const FActorInitStateChangedParams &Params)
virtual void RegisterInitStateFeature (FName &FeatureName)
virtual void UnregisterInitStateFeature (FName &FeatureName)
virtual void BindOnActorInitStateChanged (FName FeatureName, FGameplayTag RequiredState, bool bCallIfReached)
virtual bool RegisterAndCallForActorInitState (FName FeatureName, FGameplayTag RequiredState, FActorInitStateChangedBPDelegate Delegate, bool bCallImmediately=true)
virtual bool UnregisterInitStateDelegate (FActorInitStateChangedBPDelegate Delegate)
virtual FString GetDebugState (FName FeatureName) const
Protected Attributes
FDelegateHandle ActorInitStateChangedHandle
Detailed Description
Definition at line 25 of file GameInitStateInterface.h.
Member Function Documentation
BindOnActorInitStateChanged()
void IGameInitStateInterface::BindOnActorInitStateChanged (FName FeatureName, FGameplayTag RequiredState, bool bCallIfReached) virtual
Call to bind the OnActorInitStateChanged function to the appropriate delegate on the component manager
Definition at line 111 of file GameInitStateInterface.cpp.
{
    UObject* ThisObject = Cast<UObject>(this);
    AActor* OwningActor = GetOwningActor();
    UGameInitStateSubsystem* Manager = UGameInitStateSubsystem::GetForActor(OwningActor);
    if (ensure(OwningActor && Manager))
    {
        // Bind as a weak lambda because this is not a UObject but is guaranteed to be valid as long as ThisObject is
        FActorInitStateChangedDelegate Delegate = FActorInitStateChangedDelegate::CreateWeakLambda(ThisObject, [this](const FActorInitStateChangedParams& Params) { this->OnActorInitStateChanged(Params); });
        ActorInitStateChangedHandle = Manager->RegisterAndCallForActorInitState(OwningActor, FeatureName, RequiredState, MoveTemp(Delegate), bCallIfReached);
    }
}
References ActorInitStateChangedHandle, UGameInitStateSubsystem::GetForActor(), GetOwningActor(), OnActorInitStateChanged(), and UGameInitStateSubsystem::RegisterAndCallForActorInitState().
CheckDefaultInitialization()
virtual void IGameInitStateInterface::CheckDefaultInitialization () inline virtual
Override to try and progress the default initialization path, likely using ContinueInitStateChain
Definition at line 50 of file GameInitStateInterface.h.
{}
GetAllInitStatesFor()
TArray< FGameplayTag > IGameInitStateInterface::GetAllInitStatesFor (FName & FeatureName) const virtual
Returns the current feature state of this object, the default behavior is to query the manager
Definition at line 61 of file GameInitStateInterface.cpp.
{
    AActor* OwningActor = GetOwningActor();
    if (const UGameInitStateSubsystem* Manager = UGameInitStateSubsystem::GetForActor(OwningActor))
    {
        return Manager->GetAllInitStatesForFeature(OwningActor, FeatureName);
    }
    return {};
}
References UGameInitStateSubsystem::GetForActor(), and GetOwningActor().
GetCurrentInitStateFor()
FGameplayTag IGameInitStateInterface::GetCurrentInitStateFor (FName & FeatureName) const virtual
Returns the current feature state of this object, the default behavior is to query the manager
Definition at line 37 of file GameInitStateInterface.cpp.
{
    AActor* OwningActor = GetOwningActor();
    if (const UGameInitStateSubsystem* Manager = UGameInitStateSubsystem::GetForActor(OwningActor))
    {
        return Manager->GetInitStateForFeature(OwningActor, FeatureName);
    }
    return FGameplayTag();
}
References UGameInitStateSubsystem::GetForActor(), and GetOwningActor().
Referenced by GetDebugState().
GetDebugState()
FString IGameInitStateInterface::GetDebugState (FName FeatureName) const virtual
Returns Current state and any additional debug information for the active state
Definition at line 153 of file GameInitStateInterface.cpp.
{
    return FString::Printf(TEXT("CurrentState: %s"), *GetCurrentInitStateFor(FeatureName).ToString());
}
References GetCurrentInitStateFor().
GetGameInitStateSubsystem()
UGameInitStateSubsystem * IGameInitStateInterface::GetGameInitStateSubsystem () const
Gets the component manager corresponding to this object based on owning actor
Definition at line 32 of file GameInitStateInterface.cpp.
{
    return UGameInitStateSubsystem::GetForActor(GetOwningActor());
}
References UGameInitStateSubsystem::GetForActor(), and GetOwningActor().
GetOwningActor()
AActor * IGameInitStateInterface::GetOwningActor () const virtual
Returns the Actor this object is bound to, might be this object
Definition at line 10 of file GameInitStateInterface.cpp.
{
    // Removing const because most AActor functions can't handle const
    AActor* FoundActor = const_cast<AActor*>(Cast<AActor>(this));
    if (!FoundActor)
    {
        if (const UActorComponent* FoundComponent = Cast<UActorComponent>(this))
        {
            FoundActor = FoundComponent->GetOwner();
        }
    }
    if (ensure(FoundActor))
    {
        // Subclasses must implement this if they are not actors or components
        return FoundActor;
    }
    return nullptr;
}
Referenced by BindOnActorInitStateChanged(), GetAllInitStatesFor(), GetCurrentInitStateFor(), GetGameInitStateSubsystem(), HasReachedInitState(), RegisterAndCallForActorInitState(), RegisterInitStateFeature(), UnregisterInitStateDelegate(), and UnregisterInitStateFeature().
HasReachedInitState()
bool IGameInitStateInterface::HasReachedInitState (FName FeatureName, FGameplayTag DesiredState) const virtual
Checks the component manager to see if we have already reached the desired state or a later one
Definition at line 49 of file GameInitStateInterface.cpp.
{
    AActor* OwningActor = GetOwningActor();
    if (UGameInitStateSubsystem* Manager = UGameInitStateSubsystem::GetForActor(OwningActor))
    {
        return Manager->HasFeatureReachedInitState(OwningActor, FeatureName, DesiredState);
    }
    return false;
}
References UGameInitStateSubsystem::GetForActor(), and GetOwningActor().
OnActorInitStateChanged()
virtual void IGameInitStateInterface::OnActorInitStateChanged (const FActorInitStateChangedParams & Params) inline virtual
Signature for handling a game feature state, this is not registered by default
Definition at line 53 of file GameInitStateInterface.h.
{}
Referenced by BindOnActorInitStateChanged().
RegisterAndCallForActorInitState()
bool IGameInitStateInterface::RegisterAndCallForActorInitState (FName FeatureName, FGameplayTag RequiredState, FActorInitStateChangedBPDelegate Delegate, bool bCallImmediately = true) virtual
Binds a BP delegate to get called on a state change for this feature
Definition at line 127 of file GameInitStateInterface.cpp.
{
    AActor* OwningActor = GetOwningActor();
    UGameInitStateSubsystem* Manager = UGameInitStateSubsystem::GetForActor(OwningActor);
    if (ensure(OwningActor && Manager))
    {
        return Manager->RegisterAndCallForActorInitState(OwningActor, FeatureName, RequiredState, Delegate, bCallImmediately);
    }
    return false;
}
References UGameInitStateSubsystem::GetForActor(), GetOwningActor(), and UGameInitStateSubsystem::RegisterAndCallForActorInitState().
RegisterInitStateFeature()
void IGameInitStateInterface::RegisterInitStateFeature (FName & FeatureName) virtual
Call to register with the component manager during spawn if this is a game world
Definition at line 73 of file GameInitStateInterface.cpp.
{
    UObject* ThisObject = Cast<UObject>(this);
    AActor* OwningActor = GetOwningActor();
    UGameInitStateSubsystem* Manager = UGameInitStateSubsystem::GetForActor(OwningActor);
    if (OwningActor && Manager)
    {
        // Manager will be null if this isn't in a game world
        Manager->RegisterFeatureImplementer(OwningActor, FeatureName, ThisObject);
    }
}
References UGameInitStateSubsystem::GetForActor(), GetOwningActor(), and UGameInitStateSubsystem::RegisterFeatureImplementer().
UnregisterInitStateDelegate()
bool IGameInitStateInterface::UnregisterInitStateDelegate (FActorInitStateChangedBPDelegate Delegate) virtual
Unbinds a BP delegate from changes to this feature
Definition at line 141 of file GameInitStateInterface.cpp.
{
    AActor* OwningActor = GetOwningActor();
    if (UGameInitStateSubsystem* Manager = UGameInitStateSubsystem::GetForActor(OwningActor); ensure(OwningActor && Manager))
    {
        return Manager->UnregisterActorInitStateDelegate(OwningActor, Delegate);
    }
    return false;
}
References UGameInitStateSubsystem::GetForActor(), and GetOwningActor().
UnregisterInitStateFeature()
void IGameInitStateInterface::UnregisterInitStateFeature (FName & FeatureName) virtual
Unregisters state and delegate binding with component manager
Definition at line 87 of file GameInitStateInterface.cpp.
{
    UObject* ThisObject = Cast<UObject>(this);
    AActor* OwningActor = GetOwningActor();
    if (UGameInitStateSubsystem* Manager = UGameInitStateSubsystem::GetForActor(OwningActor))
    {
        if (ThisObject == OwningActor)
        {
            // This will clear all the feature states and delegates
            Manager->RemoveActorFeatureData(OwningActor);
        }
        else
        {
            Manager->RemoveFeatureImplementer(OwningActor, ThisObject);
        }
        if (ActorInitStateChangedHandle.IsValid())
        {
            Manager->UnregisterActorInitStateDelegate(OwningActor, ActorInitStateChangedHandle);
        }
    }
}
References ActorInitStateChangedHandle, UGameInitStateSubsystem::GetForActor(), and GetOwningActor().
Member Data Documentation
ActorInitStateChangedHandle
FDelegateHandle IGameInitStateInterface::ActorInitStateChangedHandle protected
Default handle created from calling BindOnActorInitStateChanged
Definition at line 77 of file GameInitStateInterface.h.
Referenced by BindOnActorInitStateChanged(), and UnregisterInitStateFeature().
The documentation for this class was generated from the following files:
Source/GameplayCore/Public/Components/GameInitStateInterface.h
Source/GameplayCore/Private/Components/GameInitStateInterface.cpp