GameplayCore Plugin: UEquipmentGameplayAbility Class Reference
UEquipmentGameplayAbility Class Reference
This class represents a gameplay ability specifically for equipment. It extends the base gameplay ability with equipment-specific functionality.
#include <EquipmentGameplayAbility.h>
Public Member Functions
UEquipmentGameplayAbility (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
UEquipmentInstance * GetSourceEquipmentInstance () const
UEquipmentInstance * GetTypedSourceEquipmentInstance (const TSubclassOf< UEquipmentInstance > &InstanceClass) const
UItemInstance * GetSourceItemInstance () const
UItemInstance * GetTypedSourceItemInstance (const TSubclassOf< UItemInstance > &InstanceClass) const
template<class T>
T * TryGetSourceObject () const
template<class T>
T * GetTypedSourceItemInstance ()
template<class T>
T * GetTypedSourceEquipmentInstance ()
Public Member Functions inherited from UGameplayAbilityBase
UGameplayAbilityBase (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
EAbilityActivationPolicy GetActivationPolicy () const
Additional Inherited Members
Protected Member Functions inherited from UGameplayAbilityBase
virtual void OnAvatarSet (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
virtual void OnGiveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
virtual void OnRemoveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
virtual void PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate *OnGameplayAbilityEndedDelegate, const FGameplayEventData *TriggerEventData) override
virtual void ActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, const FGameplayEventData *TriggerEventData) override
virtual bool CanActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayTagContainer *SourceTags, const FGameplayTagContainer *TargetTags, FGameplayTagContainer *OptionalRelevantTags) const override
virtual bool DoesAbilitySatisfyTagRequirements (const UAbilitySystemComponent &AbilitySystemComponent, const FGameplayTagContainer *SourceTags, const FGameplayTagContainer *TargetTags, FGameplayTagContainer *OptionalRelevantTags) const override
virtual void EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override
void K2_OnAbilityGiven ()
void K2_OnAbilityRemoved ()
void TryActivateAbilityOnSpawn (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) const
Protected Attributes inherited from UGameplayAbilityBase
EAbilityActivationPolicy ActivationPolicy
Detailed Description
This class represents a gameplay ability specifically for equipment. It extends the base gameplay ability with equipment-specific functionality.
See also
UGameplayAbilityBase
Definition at line 21 of file EquipmentGameplayAbility.h.
Constructor & Destructor Documentation
UEquipmentGameplayAbility()
UEquipmentGameplayAbility::UEquipmentGameplayAbility (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get())
Definition at line 11 of file EquipmentGameplayAbility.cpp.
    : Super(ObjectInitializer)
{
    InstancingPolicy = EGameplayAbilityInstancingPolicy::InstancedPerActor;
}
Member Function Documentation
GetSourceEquipmentInstance()
UEquipmentInstance * UEquipmentGameplayAbility::GetSourceEquipmentInstance () const
Gets the source equipment instance for this ability.
Returns
The UEquipmentInstance associated with this ability.
Definition at line 17 of file EquipmentGameplayAbility.cpp.
{
    return TryGetSourceObject<UEquipmentInstance>();
}
References TryGetSourceObject().
Referenced by GetSourceItemInstance().
GetSourceItemInstance()
UItemInstance * UEquipmentGameplayAbility::GetSourceItemInstance () const
Gets the source item instance for this ability.
Returns
The UItemInstance associated with this ability's equipment.
Definition at line 31 of file EquipmentGameplayAbility.cpp.
{
    if (const UEquipmentInstance* Instance = GetSourceEquipmentInstance(); IsValid(Instance))
    {
        return Cast<UItemInstance>(Instance->GetSourceItem());
    }
    return nullptr;
}
References GetSourceEquipmentInstance().
Referenced by GetTypedSourceItemInstance().
GetTypedSourceEquipmentInstance() [1/2]
template<class T> T * UEquipmentGameplayAbility::GetTypedSourceEquipmentInstance ()
Template method that retrieves the source equipment instance as the specified type.
Template Parameters
T The type to cast the equipment instance to.
Returns
The source equipment instance cast to the specified type, or nullptr if invalid.
Definition at line 101 of file EquipmentGameplayAbility.h.
{
    return TryGetSourceObject<T>();
}
References TryGetSourceObject().
GetTypedSourceEquipmentInstance() [2/2]
UEquipmentInstance * UEquipmentGameplayAbility::GetTypedSourceEquipmentInstance (const TSubclassOf< UEquipmentInstance > & InstanceClass) const
Definition at line 22 of file EquipmentGameplayAbility.cpp.
{
    if (UEquipmentInstance* Instance = TryGetSourceObject<UEquipmentInstance>(); IsValid(Instance) && Instance->IsA(InstanceClass))
    {
        return Instance;
    }
    return nullptr;
}
GetTypedSourceItemInstance() [1/2]
template<class T> T * UEquipmentGameplayAbility::GetTypedSourceItemInstance ()
Template method that retrieves the source item instance as the specified type.
Template Parameters
T The type to cast the item instance to.
Returns
The source item instance cast to the specified type, or nullptr if invalid.
Definition at line 91 of file EquipmentGameplayAbility.h.
{
    if (UItemInstance* Instance = GetSourceItemInstance(); IsValid(Instance))
    {
        return Cast<T>(Instance);
    }
    return nullptr;
}
References GetSourceItemInstance().
GetTypedSourceItemInstance() [2/2]
UItemInstance * UEquipmentGameplayAbility::GetTypedSourceItemInstance (const TSubclassOf< UItemInstance > & InstanceClass) const
Definition at line 40 of file EquipmentGameplayAbility.cpp.
{
    if (UItemInstance* Instance = GetSourceItemInstance(); IsValid(Instance) && Instance->IsA(InstanceClass))
    {
        return Instance;
    }
    return nullptr;
}
TryGetSourceObject()
template<class T> T * UEquipmentGameplayAbility::TryGetSourceObject () const
Template method that attempts to get the source object as the specified type.
Template Parameters
T The type to cast the source object to.
Returns
The source object cast to the specified type, or nullptr if invalid.
Definition at line 81 of file EquipmentGameplayAbility.h.
{
    if (UObject* const SourceObject = GetCurrentSourceObject(); IsValid(SourceObject))
    {
        return Cast<T>(SourceObject);
    }
    return nullptr;
}
Referenced by GetSourceEquipmentInstance(), and GetTypedSourceEquipmentInstance().
The documentation for this class was generated from the following files:
Source/EquipmentSystemCore/Public/Abilities/EquipmentGameplayAbility.h
Source/EquipmentSystemCore/Private/Abilities/EquipmentGameplayAbility.cpp