GameplayCore Plugin: UEquipmentInstance Class Reference
UEquipmentInstance Class Reference
Represents an instance of equipment that can be equipped by a pawn.
#include <EquipmentInstance.h>
Public Member Functions
UEquipmentInstance (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
virtual bool IsSupportedForNetworking () const override
virtual UWorld * GetWorld () const override final
virtual void GetLifetimeReplicatedProps (TArray< class FLifetimeProperty > &OutLifetimeProps) const override
APawn * GetPawn () const
APawn * GetTypedPawn (const TSubclassOf< APawn > PawnType) const
template<class T>
T * GetPawn () const
UEquipmentComponent * AddComponent (TSubclassOf< UEquipmentComponent > ComponentClass)
template<typename T>
T * AddComponent ()
const UEquipmentComponent * FindComponentByClass (TSubclassOf< UEquipmentComponent > ComponentClass) const
template<typename T>
const T * FindComponentByClass () const
UObject * GetInstigator () const
void SetInstigator (UObject *InInstigator)
UItemInstance * GetSourceItem () const
TSubclassOf< UEquipmentDefinition > GetDefinitionClass () const
UEquipmentDefinition * GetDefinition () const
virtual void SpawnActors (const TArray< FEquipmentActorSet > &ActorsToSpawn)
virtual void DestroyActors ()
TArray< AActor * > GetSpawnedActors () const
virtual void OnEquipped ()
virtual void OnUnequipped ()
virtual void OnSpawned ()
Protected Member Functions
void SetSourceItem (UItemInstance *InSourceObject)
void SetDefinition (UEquipmentDefinition *InDefinition)
void K2_OnEquipped ()
void K2_OnUnequipped ()
virtual void OnRep_Instigator ()
Protected Attributes
TArray< AActor * > SpawnedActors
TSubclassOf< UEquipmentDefinition > DefinitionClass
TObjectPtr< UEquipmentDefinition > Definition
TObjectPtr< UItemInstance > SourceItem
TArray< UEquipmentComponent * > Components
TObjectPtr< UObject > Instigator
Friends
struct FEquipmentList
class UEquipmentSlotComponent
Detailed Description
Represents an instance of equipment that can be equipped by a pawn.
See also
UObject
Definition at line 20 of file EquipmentInstance.h.
Constructor & Destructor Documentation
UEquipmentInstance()
UEquipmentInstance::UEquipmentInstance (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get())
Definition at line 14 of file EquipmentInstance.cpp.
                                                                                  : Super(ObjectInitializer.Get())
{
}
Member Function Documentation
AddComponent() [1/2]
template<typename T> T * UEquipmentInstance::AddComponent () inline
Add a new component object of class ComponentClass to this EquipmentInstance
Definition at line 57 of file EquipmentInstance.h.
    {
        return Cast<T>(AddComponent(T::StaticClass()));
    }
References AddComponent().
AddComponent() [2/2]
UEquipmentComponent * UEquipmentInstance::AddComponent (TSubclassOf< UEquipmentComponent > ComponentClass)
Add a new component object of class ComponentClass to this EquipmentInstance
Parameters
ComponentClass Class of the EquipmentComponent to search
Definition at line 53 of file EquipmentInstance.cpp.
{
    if (const auto Component = NewObject<UEquipmentComponent>(ComponentClass); IsValid(Component))
    {
        Components.Add(Component);
        return Component;
    }
    return nullptr;
}
References Components.
Referenced by AddComponent().
DestroyActors()
void UEquipmentInstance::DestroyActors () virtual
Destroy all actors spawned by this equipment instance.
Definition at line 155 of file EquipmentInstance.cpp.
{
    for (AActor* Actor : SpawnedActors)
    {
        if (IsValid(Actor))
        {
            Actor->Destroy();
        }
    }
}
Referenced by FEquipmentList::Remove().
FindComponentByClass() [1/2]
template<typename T> const T * UEquipmentInstance::FindComponentByClass () const inline
Try to find fragment of class ComponentClass of this equipment instance
Definition at line 72 of file EquipmentInstance.h.
    {
        return Cast<T*>(FindComponentByClass(T::StaticClass()));
    }
References FindComponentByClass().
FindComponentByClass() [2/2]
const UEquipmentComponent * UEquipmentInstance::FindComponentByClass (TSubclassOf< UEquipmentComponent > ComponentClass) const
Try to find component of class ComponentClass of this equipment instance
Parameters
ComponentClass Class of the Equipment Instance's component to search
Definition at line 63 of file EquipmentInstance.cpp.
{
    if (IsValid(ComponentClass))
    {
        for (const UEquipmentComponent* Component : Components)
        {
            if (IsValid(Component) && Component->IsA(ComponentClass))
            {
                return Component;
            }
        }
    }
    return nullptr;
}
References Components.
Referenced by FindComponentByClass().
GetDefinition()
UEquipmentDefinition * UEquipmentInstance::GetDefinition () const
Gets the equipment definition associated with this instance, cached by the Equipment System Component.
Returns
The equipment definition default object.
Definition at line 99 of file EquipmentInstance.cpp.
{
    return Definition.Get();
}
References Definition.
GetDefinitionClass()
TSubclassOf< UEquipmentDefinition > UEquipmentInstance::GetDefinitionClass () const
Gets the equipment definition class associated with this instance.
Returns
The equipment definition class.
Definition at line 94 of file EquipmentInstance.cpp.
{
    return DefinitionClass;
}
References DefinitionClass.
GetInstigator()
UObject * UEquipmentInstance::GetInstigator () const
Get the instigator object that caused this equipment instance to be equipped.
Definition at line 79 of file EquipmentInstance.cpp.
{
    return Instigator;
}
GetLifetimeReplicatedProps()
void UEquipmentInstance::GetLifetimeReplicatedProps (TArray< class FLifetimeProperty > & OutLifetimeProps) const override virtual
Definition at line 27 of file EquipmentInstance.cpp.
{
    UObject::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(ThisClass, Instigator);
    DOREPLIFETIME(ThisClass, SpawnedActors);
    DOREPLIFETIME(ThisClass, Components);
}
GetPawn() [1/2]
APawn * UEquipmentInstance::GetPawn () const
Get the pawn that this equipment instance is attached to.
Definition at line 36 of file EquipmentInstance.cpp.
{
    return Cast<APawn>(GetOuter());
}
Referenced by SpawnActors().
GetPawn() [2/2]
template<class T> T * UEquipmentInstance::GetPawn () const inline
Get the pawn that this equipment instance is attached to, if applicable.
Definition at line 44 of file EquipmentInstance.h.
{ return Cast<T>(GetPawn()); }
References GetPawn().
Referenced by GetPawn().
GetSourceItem()
UItemInstance * UEquipmentInstance::GetSourceItem () const
Get the source object that caused this equipment instance to be equipped. (ItemInstance class)
Definition at line 89 of file EquipmentInstance.cpp.
{
    return SourceItem;
}
GetSpawnedActors()
TArray< AActor * > UEquipmentInstance::GetSpawnedActors () const inline
Get an array of actors spawned by this equipment instance.
Definition at line 109 of file EquipmentInstance.h.
{ return SpawnedActors; }
References GetSpawnedActors().
Referenced by GetSpawnedActors().
GetTypedPawn()
APawn * UEquipmentInstance::GetTypedPawn (const TSubclassOf< APawn > PawnType) const
Get the pawn that this equipment instance is attached to, if applicable.
Definition at line 41 of file EquipmentInstance.cpp.
{
    if (UClass* PawnClass = Type->GetClass())
    {
        if (GetOuter()->IsA(PawnClass))
        {
            return Cast<APawn>(GetOuter());
        }
    }
    return nullptr;
}
GetWorld()
UWorld * UEquipmentInstance::GetWorld () const final override virtual
Definition at line 18 of file EquipmentInstance.cpp.
{
    if (const APawn* OwningPawn = GetPawn(); IsValid(OwningPawn))
    {
        return OwningPawn->GetWorld();
    }
    return nullptr;
}
IsSupportedForNetworking()
virtual bool UEquipmentInstance::IsSupportedForNetworking () const inline override virtual
Definition at line 31 of file EquipmentInstance.h.
{ return true; }
K2_OnEquipped()
void UEquipmentInstance::K2_OnEquipped () protected
Blueprint event called when this equipment instance is equipped.
References K2_OnEquipped().
Referenced by K2_OnEquipped(), and OnEquipped().
K2_OnUnequipped()
void UEquipmentInstance::K2_OnUnequipped () protected
Blueprint event called when this equipment instance is unequipped.
References K2_OnUnequipped().
Referenced by K2_OnUnequipped(), and OnUnequipped().
OnEquipped()
void UEquipmentInstance::OnEquipped () virtual
Called the equipment instance is equipped.
Definition at line 166 of file EquipmentInstance.cpp.
{
    K2_OnEquipped();
}
References K2_OnEquipped().
OnRep_Instigator()
void UEquipmentInstance::OnRep_Instigator () protected virtual
Definition at line 180 of file EquipmentInstance.cpp.
{
}
OnSpawned()
void UEquipmentInstance::OnSpawned () virtual
Called the equipment instance is spawned.
Definition at line 176 of file EquipmentInstance.cpp.
{
}
Referenced by FEquipmentList::Add().
OnUnequipped()
void UEquipmentInstance::OnUnequipped () virtual
Called the equipment instance is unequipped.
Definition at line 171 of file EquipmentInstance.cpp.
{
    K2_OnUnequipped();
}
References K2_OnUnequipped().
Referenced by UEquipmentSystemComponent::UnequipItem().
SetDefinition()
void UEquipmentInstance::SetDefinition (UEquipmentDefinition * InDefinition) protected
Sets the item definition class for this instance.
Parameters
InDefinition - The item definition to set.
Definition at line 109 of file EquipmentInstance.cpp.
{
    Definition = InDefinition;
    DefinitionClass = InDefinition->GetClass();
}
References Definition, and DefinitionClass.
Referenced by FEquipmentList::Add().
SetInstigator()
void UEquipmentInstance::SetInstigator (UObject * InInstigator)
Set the instigator object for this equipment instance.
Definition at line 84 of file EquipmentInstance.cpp.
{
    Instigator = InInstigator;
}
Referenced by FEquipmentList::Add().
SetSourceItem()
void UEquipmentInstance::SetSourceItem (UItemInstance * InSourceObject) protected
Set the source object for this equipment instance. (ItemInstance class)
Definition at line 104 of file EquipmentInstance.cpp.
{
    SourceItem = InSourceObject;
}
SpawnActors()
void UEquipmentInstance::SpawnActors (const TArray< FEquipmentActorSet > & ActorsToSpawn) virtual
Spawn actors defined in the given array and attach them to the pawn.
Parameters
ActorsToSpawn Array of actor sets defining which actors to spawn and how to attach them.
Definition at line 115 of file EquipmentInstance.cpp.
{
    UWorld* World = GetWorld();
    verifyf(IsValid(World), TEXT("Invalid world to spawn actors for %s"), *GetName());
    if (APawn* OwningPawn = GetPawn(); IsValid(OwningPawn))
    {
        // Use root scene component as attachment target by default
        USceneComponent* AttachTarget = OwningPawn->GetRootComponent();
        if (const ACharacter* Character = Cast<ACharacter>(OwningPawn))
        {
            AttachTarget = Character->GetMesh();
        }
        for (const auto& [SlotTag, ActorClass, AttachSocket, AttachTransform] : ActorsToSpawn)
        {
            if (!IsValid(ActorClass))
            {
                UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to spawn equipment actors with an invalid actor class for %s!"), *GetName());
                continue;
            }
            if (const auto NewActor = World->SpawnActorDeferred<AActor>(ActorClass, FTransform::Identity, OwningPawn); IsValid(NewActor))
            {
                NewActor->SetInstigator(OwningPawn);
                NewActor->FinishSpawning(FTransform::Identity, true);
                // Set relative transform before attaching
                NewActor->SetActorRelativeTransform(AttachTransform);
                NewActor->AttachToComponent(AttachTarget, FAttachmentTransformRules::KeepRelativeTransform, AttachSocket);
                SpawnedActors.Add(NewActor);
            }
        }
        return;
    }
    UE_LOG(LogEquipmentSystem, Error, TEXT("Tried to spawn equipment actors with an invalid pawn !"));
}
References GetPawn().
Referenced by FEquipmentList::Add().
Friends And Related Symbol Documentation
FEquipmentList
friend struct FEquipmentList friend
Definition at line 24 of file EquipmentInstance.h.
UEquipmentSlotComponent
friend class UEquipmentSlotComponent friend
Definition at line 25 of file EquipmentInstance.h.
Member Data Documentation
Components
TArray<UEquipmentComponent*> UEquipmentInstance::Components protected
Array of components attached to this item instance.
Definition at line 161 of file EquipmentInstance.h.
Referenced by AddComponent(), and FindComponentByClass().
Definition
TObjectPtr<UEquipmentDefinition> UEquipmentInstance::Definition protected
The Equipment Definition default object, cached by the local EquipmentSystemComponent cache
Definition at line 154 of file EquipmentInstance.h.
Referenced by GetDefinition(), and SetDefinition().
DefinitionClass
TSubclassOf<UEquipmentDefinition> UEquipmentInstance::DefinitionClass protected
The Equipment definition that this instance is based on. Only replicate the class.
Definition at line 150 of file EquipmentInstance.h.
Referenced by GetDefinitionClass(), and SetDefinition().
Instigator
TObjectPtr<UObject> UEquipmentInstance::Instigator protected
Definition at line 164 of file EquipmentInstance.h.
SourceItem
TObjectPtr<UItemInstance> UEquipmentInstance::SourceItem protected
Definition at line 157 of file EquipmentInstance.h.
SpawnedActors
TArray<AActor*> UEquipmentInstance::SpawnedActors protected
Definition at line 144 of file EquipmentInstance.h.
The documentation for this class was generated from the following files:
Source/EquipmentSystemCore/Public/Instances/EquipmentInstance.h
Source/EquipmentSystemCore/Private/Instances/EquipmentInstance.cpp