GameplayCore Plugin: FAbilitySetHandles Struct Reference
FAbilitySetHandles Struct Reference
#include <AbilitySetHandles.h>
Public Member Functions
void AddAbilitySpecHandle (const FGameplayAbilitySpecHandle &Handle)
void AddGameplayEffectHandle (const FActiveGameplayEffectHandle &Handle)
void AddAttributeSet (UAttributeSet *Set)
void TakeFromAbilitySystem (UAbilitySystemComponent *AbilitySystemComp)
Protected Attributes
TArray< FGameplayAbilitySpecHandle > AbilitySpecHandles
TArray< FActiveGameplayEffectHandle > GameplayEffectHandles
TArray< TObjectPtr< UAttributeSet > > GrantedAttributeSets
Detailed Description
FAbilitySetHandles
Data used to store handles to what has been granted by the ability set.
Definition at line 18 of file AbilitySetHandles.h.
Member Function Documentation
AddAbilitySpecHandle()
void FAbilitySetHandles::AddAbilitySpecHandle (const FGameplayAbilitySpecHandle & Handle)
Adds a gameplay ability spec handle to the set.
Parameters
Handle The gameplay ability spec handle to add.
Definition at line 10 of file AbilitySetHandles.cpp.
{
    if (Handle.IsValid())
    {
        AbilitySpecHandles.Add(Handle);
    }
}
References AbilitySpecHandles.
Referenced by UAbilitySet::GiveToAbilitySystem().
AddAttributeSet()
void FAbilitySetHandles::AddAttributeSet (UAttributeSet * Set)
Adds an attribute set to the granted sets.
Parameters
Set The attribute set to add.
Definition at line 26 of file AbilitySetHandles.cpp.
{
    GrantedAttributeSets.Add(Set);
}
References GrantedAttributeSets.
Referenced by UAbilitySet::GiveToAbilitySystem().
AddGameplayEffectHandle()
void FAbilitySetHandles::AddGameplayEffectHandle (const FActiveGameplayEffectHandle & Handle)
Adds a gameplay effect handle to the set.
Parameters
Handle The gameplay effect handle to add.
Definition at line 18 of file AbilitySetHandles.cpp.
{
    if (Handle.IsValid())
    {
        GameplayEffectHandles.Add(Handle);
    }
}
References GameplayEffectHandles.
Referenced by UAbilitySet::GiveToAbilitySystem().
TakeFromAbilitySystem()
void FAbilitySetHandles::TakeFromAbilitySystem (UAbilitySystemComponent * AbilitySystemComp)
Removes all granted abilities, effects, and attributes from the given ability system component.
Parameters
AbilitySystemComp The ability system component to remove granted items from.
Definition at line 31 of file AbilitySetHandles.cpp.
{
    check(AbilitySystemComp);
    ensure(!AbilitySystemComp->IsOwnerActorAuthoritative());
    for (const FGameplayAbilitySpecHandle& Handle : AbilitySpecHandles)
    {
        if (Handle.IsValid())
        {
            AbilitySystemComp->ClearAbility(Handle);
        }
    }
    for (const FActiveGameplayEffectHandle& Handle : GameplayEffectHandles)
    {
        if (Handle.IsValid())
        {
            AbilitySystemComp->RemoveActiveGameplayEffect(Handle);
        }
    }
    for (UAttributeSet* Set : GrantedAttributeSets)
    {
        AbilitySystemComp->RemoveSpawnedAttribute(Set);
    }
    AbilitySpecHandles.Reset();
    GameplayEffectHandles.Reset();
    GrantedAttributeSets.Reset();
}
References AbilitySpecHandles, GameplayEffectHandles, and GrantedAttributeSets.
Referenced by FEquipmentList::Remove().
Member Data Documentation
AbilitySpecHandles
TArray<FGameplayAbilitySpecHandle> FAbilitySetHandles::AbilitySpecHandles protected
Handles to the granted abilities.
Definition at line 47 of file AbilitySetHandles.h.
Referenced by AddAbilitySpecHandle(), and TakeFromAbilitySystem().
GameplayEffectHandles
TArray<FActiveGameplayEffectHandle> FAbilitySetHandles::GameplayEffectHandles protected
Handles to the granted gameplay effects.
Definition at line 51 of file AbilitySetHandles.h.
Referenced by AddGameplayEffectHandle(), and TakeFromAbilitySystem().
GrantedAttributeSets
TArray<TObjectPtr<UAttributeSet> > FAbilitySetHandles::GrantedAttributeSets protected
Pointers to the granted attribute sets.
Definition at line 55 of file AbilitySetHandles.h.
Referenced by AddAttributeSet(), and TakeFromAbilitySystem().
The documentation for this struct was generated from the following files:
Source/AbilitySystemCore/Public/Data/AbilitySetHandles.h
Source/AbilitySystemCore/Private/Data/AbilitySetHandles.cpp