GameplayCore Plugin: FEquipmentList Struct Reference
FEquipmentList Struct Reference
Represents a list of equipment items that can be efficiently replicated using FastArraySerializer.
#include <EquipmentList.h>
Public Member Functions
FEquipmentList (UEquipmentSystemComponent *InOwnerComponent)
void PreReplicatedRemove (const TArrayView< int32 > RemovedIndices, int32 FinalSize)
void PostReplicatedAdd (const TArrayView< int32 > AddedIndices, int32 FinalSize)
void PostReplicatedChange (const TArrayView< int32 > ChangedIndices, int32 FinalSize)
bool NetDeltaSerialize (FNetDeltaSerializeInfo &DeltaParms)
FEquipmentResult Add (const TSubclassOf< UEquipmentDefinition > &DefinitionClass, UItemInstance *SourceItemInstance=nullptr)
void Remove (UEquipmentInstance *Instance, FGameplayTag &OutFailureReason)
Public Attributes
friend FEquipmentEntry
Protected Member Functions
void Internal_OnEntryChanged (int32 Index, const FEquipmentEntry &Entry) const
void Internal_OnEntryAdded (int32 Index, const FEquipmentEntry &Entry) const
void Internal_OnEntryRemoved (int32 Index, const FEquipmentEntry &Entry) const
UAbilitySystemComponent * GetAbilitySystemComponent () const
Protected Attributes
TArray< FEquipmentEntry > Entries
TObjectPtr< UEquipmentSystemComponent > OwnerComponent = nullptr
Friends
class UEquipmentSystemComponent
Detailed Description
Represents a list of equipment items that can be efficiently replicated using FastArraySerializer.
See also
FFastArraySerializer
Definition at line 42 of file EquipmentList.h.
Constructor & Destructor Documentation
FEquipmentList() [1/2]
FEquipmentList::FEquipmentList ()
Definition at line 15 of file EquipmentList.cpp.
{
}
FEquipmentList() [2/2]
FEquipmentList::FEquipmentList (UEquipmentSystemComponent * InOwnerComponent)
Definition at line 19 of file EquipmentList.cpp.
    : OwnerComponent(InOwnerComponent)
{
}
~FEquipmentList()
FEquipmentList::~FEquipmentList ()
Definition at line 24 of file EquipmentList.cpp.
{
    Entries.Empty();
}
Member Function Documentation
Add()
FEquipmentResult FEquipmentList::Add (const TSubclassOf< UEquipmentDefinition > & DefinitionClass, UItemInstance * SourceItemInstance = nullptr)
Add a new equipment instance to the list.
Parameters
DefinitionClass Definition of the type of equipment to add.
SourceItemInstance
OutFailureReason
Returns
Pointer to entry added
Definition at line 81 of file EquipmentList.cpp.
{
    FEquipmentResult Result;
    if (DefinitionClass == nullptr || !IsValid(OwnerComponent))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to instantiate an equipment instance from invalid definition class."));
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_MissingDefinition;
        return Result;
    }
    AActor* OwnerActor = OwnerComponent->GetOwner();
    if (!OwnerActor->HasAuthority())
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to instantiate an equipment instance from invalid definition class."));
        Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_NotAuthority;
        return Result;
    }
    UEquipmentDefinition* CachedDefinition = OwnerComponent->GetCachedDefinition(DefinitionClass);
    if (!CachedDefinition->CanBeEquipped(OwnerComponent, Result.FailureReason))
    {
        UE_LOG(LogEquipmentSystem, Warning, TEXT("Tried to instantiate an equipment instance from %s, but the definition conditions are not met."), *GetNameSafe(DefinitionClass));
        if (!Result.FailureReason.IsValid())
            Result.FailureReason = EquipmentSystemGameplayTags::TAG_Equipment_Failure_DefinitionRefused;
        return Result;
    }
    // Prepare an instance type to spawn, use the default one by default
    TSubclassOf<UEquipmentInstance> InstanceType = CachedDefinition->InstanceClass;
    if (InstanceType == nullptr)
    {
        InstanceType = UEquipmentDefinition::StaticClass();
    }
    // Add default entry
    FEquipmentEntry& Entry = Entries.AddDefaulted_GetRef();
    Entry.EquipmentDefinition = DefinitionClass;
    Entry.Instance = NewObject<UEquipmentInstance>(OwnerActor, InstanceType);
    UEquipmentInstance* Instance = Entry.Instance;
    Instance->SetDefinition(CachedDefinition);
    Instance->SetInstigator(OwnerActor);
    Instance->SetSourceItem(SourceItemInstance);
    Result.Instance = Instance;
    // Give the ability sets
    if (UAbilitySystemComponent* AbilitySystemComp = GetAbilitySystemComponent())
    {
        for (const TObjectPtr<const UAbilitySet>& AbilitySet : CachedDefinition->AbilitySets)
        {
            AbilitySet->GiveToAbilitySystem(AbilitySystemComp, &Entry.Handles, Instance);
        }
    }
    // Ask the instance to spawn attachment actors
    Instance->SpawnActors(CachedDefinition->ActorsToSpawn);
    Instance->OnSpawned();
    // Mark the item dirty for the serializer replication
    MarkItemDirty(Entry);
    return Result;
}
References UEquipmentDefinition::AbilitySets, UEquipmentDefinition::ActorsToSpawn, Entries, GetAbilitySystemComponent(), UEquipmentDefinition::InstanceClass, UEquipmentInstance::OnSpawned(), OwnerComponent, UEquipmentInstance::SetDefinition(), UEquipmentInstance::SetInstigator(), UEquipmentInstance::SetSourceItem(), and UEquipmentInstance::SpawnActors().
GetAbilitySystemComponent()
UAbilitySystemComponent * FEquipmentList::GetAbilitySystemComponent () const protected
Get the ability system component of the owner.
Definition at line 202 of file EquipmentList.cpp.
{
    check(OwnerComponent);
    const AActor* OwningActor = OwnerComponent->GetOwner();
    return UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(OwningActor);
}
References OwnerComponent.
Referenced by Add(), and Remove().
Internal_OnEntryAdded()
void FEquipmentList::Internal_OnEntryAdded (int32 Index, const FEquipmentEntry & Entry) const protected
Called when an entry is added.
Parameters
Index The index of the added entry.
Entry The added entry.
Definition at line 178 of file EquipmentList.cpp.
{
    FEquipmentChangeData Data;
    Data.Index = Index;
    Data.NewInstance = Entry.Instance;
    Data.OldInstance = nullptr;
    Data.ChangeType = EEquipmentChangeType::Equipped;
    OwnerComponent->PostEquipmentEquipped(Data);
    OwnerComponent->PostEquipmentChanged(Data);
}
References FEquipmentChangeData::ChangeType, FEquipmentChangeData::Index, FEquipmentChangeData::NewInstance, FEquipmentChangeData::OldInstance, and OwnerComponent.
Internal_OnEntryChanged()
void FEquipmentList::Internal_OnEntryChanged (int32 Index, const FEquipmentEntry & Entry) const protected
Called when an entry is changed.
Parameters
Index The index of the changed entry.
Entry The changed entry.
Definition at line 167 of file EquipmentList.cpp.
{
    FEquipmentChangeData Data;
    Data.Index = Index;
    Data.NewInstance = Entry.Instance;
    Data.OldInstance = nullptr;
    Data.ChangeType = EEquipmentChangeType::Modified;
    OwnerComponent->PostEquipmentChanged(Data);
}
References FEquipmentChangeData::ChangeType, FEquipmentChangeData::Index, FEquipmentChangeData::NewInstance, FEquipmentChangeData::OldInstance, and OwnerComponent.
Internal_OnEntryRemoved()
void FEquipmentList::Internal_OnEntryRemoved (int32 Index, const FEquipmentEntry & Entry) const protected
Called when an entry is removed.
Parameters
Index The index of the removed entry.
Entry The removed entry.
Definition at line 190 of file EquipmentList.cpp.
{
    FEquipmentChangeData Data;
    Data.Index = Index;
    Data.NewInstance = nullptr;
    Data.OldInstance = Entry.Instance;
    Data.ChangeType = EEquipmentChangeType::Unequipped;
    OwnerComponent->PostEquipmentUnequipped(Data);
    OwnerComponent->PostEquipmentChanged(Data);
}
References FEquipmentChangeData::ChangeType, FEquipmentChangeData::Index, FEquipmentChangeData::NewInstance, FEquipmentChangeData::OldInstance, and OwnerComponent.
NetDeltaSerialize()
bool FEquipmentList::NetDeltaSerialize (FNetDeltaSerializeInfo & DeltaParms) inline
Implements network delta serialization for the equipment list.
Definition at line 59 of file EquipmentList.h.
{ return FastArrayDeltaSerialize<FEquipmentEntry, FEquipmentList>(Entries, DeltaParms, *this); }
References Entries.
PostReplicatedAdd()
void FEquipmentList::PostReplicatedAdd (const TArrayView< int32 > AddedIndices, int32 FinalSize)
Definition at line 43 of file EquipmentList.cpp.
{
    for (const int32 Index : AddedIndices)
    {
        if (FEquipmentEntry& Entry = Entries[Index]; Entry.Instance != nullptr)
        {
            Entry.Instance->OnEquipped();
            Entry.LastInstance = MakeWeakObjectPtr<UEquipmentInstance>(Entry.Instance);
            Internal_OnEntryAdded(Index, Entry);
        }
    }
}
PostReplicatedChange()
void FEquipmentList::PostReplicatedChange (const TArrayView< int32 > ChangedIndices, int32 FinalSize)
Definition at line 57 of file EquipmentList.cpp.
{
    for (const int32 Index : ChangedIndices)
    {
        if (Entries.IsValidIndex(Index))
        {
            FEquipmentEntry& Entry = Entries[Index];
            if (IsValid(Entry.Instance))
            {
                Entry.Instance->OnEquipped();
            }
            if (Entry.Instance != Entry.LastInstance.Get() && Entry.LastInstance.IsValid())
            {
                Entry.LastInstance->OnUnequipped();
                Entry.LastInstance = MakeWeakObjectPtr<UEquipmentInstance>(Entry.Instance);
            }
            Internal_OnEntryChanged(Index, Entry);
        }
    }
}
PreReplicatedRemove()
void FEquipmentList::PreReplicatedRemove (const TArrayView< int32 > RemovedIndices, int32 FinalSize)
Definition at line 29 of file EquipmentList.cpp.
{
    for (const int32 Index : RemovedIndices)
    {
        if (FEquipmentEntry& Entry = Entries[Index]; Entry.Instance != nullptr)
        {
            Entry.Instance->OnUnequipped();
            Entry.LastInstance = nullptr;
            Internal_OnEntryRemoved(Index, Entry);
        }
    }
}
Remove()
void FEquipmentList::Remove (UEquipmentInstance * Instance, FGameplayTag & OutFailureReason)
Remove the specified equipment instance from the list.
Parameters
Instance The instance to remove.
OutFailureReason
Definition at line 147 of file EquipmentList.cpp.
{
    for (auto EntryIterator = Entries.CreateIterator(); EntryIterator; ++EntryIterator)
    {
        if (FEquipmentEntry& Entry = *EntryIterator; Entry.Instance == Instance)
        {
            if (UAbilitySystemComponent* AbilitySystemComp = GetAbilitySystemComponent())
            {
                Entry.Handles.TakeFromAbilitySystem(AbilitySystemComp);
            }
            // Ask the instance to destroy its attachment actors
            Instance->DestroyActors();
            EntryIterator.RemoveCurrent();
            MarkArrayDirty();
        }
    }
}
References UEquipmentInstance::DestroyActors(), Entries, GetAbilitySystemComponent(), and FAbilitySetHandles::TakeFromAbilitySystem().
Friends And Related Symbol Documentation
UEquipmentSystemComponent
friend class UEquipmentSystemComponent friend
Definition at line 46 of file EquipmentList.h.
Member Data Documentation
Entries
TArray<FEquipmentEntry> FEquipmentList::Entries protected
Array of equipment entries
Definition at line 104 of file EquipmentList.h.
Referenced by Add(), NetDeltaSerialize(), and Remove().
FEquipmentEntry
friend FEquipmentList::FEquipmentEntry
Definition at line 47 of file EquipmentList.h.
OwnerComponent
TObjectPtr<UEquipmentSystemComponent> FEquipmentList::OwnerComponent = nullptr protected
Owner component of this equipment list
Definition at line 108 of file EquipmentList.h.
Referenced by Add(), GetAbilitySystemComponent(), Internal_OnEntryAdded(), Internal_OnEntryChanged(), and Internal_OnEntryRemoved().
The documentation for this struct was generated from the following files:
Source/EquipmentSystemCore/Public/Data/EquipmentList.h
Source/EquipmentSystemCore/Private/Data/EquipmentList.cpp