GameplayCore Plugin: FInventoryList Class Reference
FInventoryList Class Reference
A replicated container that manages a list of inventory entries.
#include <InventoryList.h>
Public Member Functions
FInventoryList (UInventorySystemComponent *InOwnerComponent)
void PreReplicatedRemove (const TArrayView< int32 > RemovedIndices, int32 FinalSize)
void PostReplicatedAdd (const TArrayView< int32 > AddedIndices, int32 FinalSize)
void PostReplicatedChange (const TArrayView< int32 > ChangedIndices, int32 FinalSize)
bool NetDeltaSerialize (FNetDeltaSerializeInfo &DeltaParams)
FInventoryAddResult Add (const TSubclassOf< UItemDefinition > &DefinitionClass, int32 Count=1)
void Remove (UItemInstance *Instance, FGameplayTag &OutFailureReason)
FInventoryAddResult AddItemInstance (UItemInstance *ItemInstance, int32 Count=1)
void AddItemInstance (const FInventoryEntry &Entry, FGameplayTag &OutFailureReason)
FInventoryEntryHandle FindHandleOfType (const TSubclassOf< UItemDefinition > &ItemDefinition)
TArray< FInventoryEntryHandle > GetHandlesOfType (const TSubclassOf< UItemDefinition > &ItemDefinition)
TArray< FInventoryEntryHandle > GetAllHandles () const
FInventoryEntry * FindEntryOfType (const TSubclassOf< UItemDefinition > &ItemDefinition)
Static Public Member Functions
static TArray< FInventoryEntry * > GetEntriesOfType (const TSubclassOf< UItemDefinition > &ItemDefinition)
static TArray< FInventoryEntry * > GetAllEntries ()
Public Attributes
friend FInventoryEntry
Protected Member Functions
UItemInstance * CreateItemInstance (const TSubclassOf< UItemDefinition > &DefinitionClass, int32 &Count)
bool CanAdd (const TSubclassOf< UItemDefinition > &DefinitionClass, FGameplayTag &OutFailureReason, int32 InCount=1)
void Internal_OnEntryChanged (int32 Index, const FInventoryEntry &Entry) const
void Internal_OnEntryAdded (int32 Index, const FInventoryEntry &Entry) const
void Internal_OnEntryRemoved (int32 Index, const FInventoryEntry &Entry) const
Protected Attributes
TArray< FInventoryEntry > Entries
TObjectPtr< UInventorySystemComponent > OwnerComponent = nullptr
Friends
class UInventorySystemComponent
Detailed Description
A replicated container that manages a list of inventory entries.
See also
FFastArraySerializer
Handles the storage, replication, and management of inventory entries including addition, removal, and modification of items. Utilizes FastArraySerializer for efficient network replication and provides interfaces for item manipulation and querying.
Definition at line 46 of file InventoryList.h.
Constructor & Destructor Documentation
FInventoryList() [1/2]
FInventoryList::FInventoryList ()
Definition at line 13 of file InventoryList.cpp.
    : OwnerComponent(nullptr)
{
}
FInventoryList() [2/2]
FInventoryList::FInventoryList (UInventorySystemComponent * InOwnerComponent)
Definition at line 18 of file InventoryList.cpp.
    : OwnerComponent(InOwnerComponent)
{
}
Member Function Documentation
Add()
FInventoryAddResult FInventoryList::Add (const TSubclassOf< UItemDefinition > & DefinitionClass, int32 Count = 1)
Adds an item to the inventory list from its definition.
Parameters
DefinitionClass The item definition class to add.
Count The number of items to add.
Returns
Item instances if added successfully, otherwise returns an empty array.
Definition at line 66 of file InventoryList.cpp.
{
    FInventoryAddResult Result;
    if (!IsValid(DefinitionClass) || !OwnerComponent)
    {
        UE_LOG(LogInventorySystem, Warning, TEXT("Tried to instantiate an item instance from invalid definition class."));
        Result.FailureReason = InventorySystemGameplayTags::TAG_Inventory_Failure_NullDefinition;
        return Result;
    }
    if (const AActor* OwnerActor = OwnerComponent->GetOwner(); !OwnerActor->HasAuthority())
    {
        UE_LOG(LogInventorySystem, Warning, TEXT("Tried to instantiate an item instance from invalid definition class."));
        Result.FailureReason = InventorySystemGameplayTags::TAG_Inventory_Failure_NotAuthority;
        return Result;
    }
    // Check validity of the definition instance, and storable fragments
    if (!CanAdd(DefinitionClass, Result.FailureReason, Count))
    {
        return Result;
    }
    int32 RemainingCount = Count;
    const UItemDefinition* CachedDefinition = OwnerComponent->GetCachedDefinition(DefinitionClass);
    const UItemFragment_Storable* StorableFragment = CachedDefinition->FindFragmentByClass<UItemFragment_Storable>();
    // Handles stacking if the object is stackable
    if (StorableFragment->CanStack())
    {
        for (int32 Index = 0; Index < Entries.Num() && RemainingCount > 0; ++Index)
        {
            FInventoryEntry& Entry = Entries[Index];
            if (Entry.Instance->DefinitionClass != DefinitionClass)
            {
                continue;
            }
            const int32 FreeCount = StorableFragment->MaxStackCount - Entry.StackCount;
            const int32 ToAdd = FMath::Min(RemainingCount, FreeCount);
            if (ToAdd > 0)
            {
                Entry.StackCount += ToAdd;
                RemainingCount -= ToAdd;
                Internal_OnEntryChanged(Index, Entry);
                Entry.LastStackCount = Entry.StackCount;
                MarkItemDirty(Entry);
                Result.Instances.Add(Entry.Instance);
            }
        }
    }
    // Calculate the number of new stacks required
    const int32 MaxStackCount = StorableFragment->CanStack() ? StorableFragment->MaxStackCount : 1;
    const int32 NeededStacks = FMath::DivideAndRoundUp(RemainingCount, MaxStackCount);
    // Create new stacks for the rest
    for (int32 i = 0; i < NeededStacks && RemainingCount > 0; ++i)
    {
        if (!CanAdd(DefinitionClass, Result.FailureReason, RemainingCount))
        {
            break;
        }
        int32 CurrentCount = RemainingCount;
        if (UItemInstance* NewInstance = CreateItemInstance(DefinitionClass, CurrentCount))
        {
            Result.Instances.Add(NewInstance);
            RemainingCount = CurrentCount;
        }
    }
    return Result;
}
References CanAdd(), UItemFragment_Storable::CanStack(), Entries, UItemDefinition::FindFragmentByClass(), Internal_OnEntryChanged(), UItemFragment_Storable::MaxStackCount, and OwnerComponent.
AddItemInstance() [1/2]
void FInventoryList::AddItemInstance (const FInventoryEntry & Entry, FGameplayTag & OutFailureReason)
Definition at line 193 of file InventoryList.cpp.
{
    AddItemInstance(Entry.Instance, Entry.StackCount);
}
AddItemInstance() [2/2]
FInventoryAddResult FInventoryList::AddItemInstance (UItemInstance * ItemInstance, int32 Count = 1)
Definition at line 159 of file InventoryList.cpp.
{
    FInventoryAddResult Result;
    if (!IsValid(ItemInstance))
    {
        Result.FailureReason = InventorySystemGameplayTags::TAG_Inventory_Failure_NullInstance;
        return Result;
    }
    // Check if the item can be added
    if (const TSubclassOf<UItemDefinition> DefinitionClass = ItemInstance->GetDefinitionClass())
    {
        if (!CanAdd(DefinitionClass, Result.FailureReason, Count))
            return Result;
    }
    // Creating and configuring the new input
    FInventoryEntry& NewEntry = Entries.AddDefaulted_GetRef();
    const int32 NewIndex = Entries.Num() - 1;
    NewEntry.Instance = ItemInstance;
    NewEntry.StackCount = Count;
    NewEntry.LastStackCount = Count;
    Result.Instances.Add(ItemInstance);
    // Notification du changement
    Internal_OnEntryAdded(NewIndex, NewEntry);
    MarkItemDirty(NewEntry);
    return Result;
}
CanAdd()
bool FInventoryList::CanAdd (const TSubclassOf< UItemDefinition > & DefinitionClass, FGameplayTag & OutFailureReason, int32 InCount = 1) protected
Checks if an item of the specified definition can be added
Parameters
DefinitionClass The item definition class to check
OutFailureReason
InCount
Returns
True if the item can be added, false otherwise
Definition at line 336 of file InventoryList.cpp.
{
    UItemDefinition* CachedDefinition = OwnerComponent->GetCachedDefinition(DefinitionClass);
    if (!IsValid(CachedDefinition))
    {
        UE_LOG(LogInventorySystem, Warning, TEXT("Tried to instantiate an item instance from invalid definition class."));
        OutFailureReason = InventorySystemGameplayTags::TAG_Inventory_Failure_NullDefinition;
        return false;
    }
    if (!CachedDefinition->CanBeGiven(OwnerComponent, OutFailureReason))
    {
        UE_LOG(LogInventorySystem, Warning, TEXT("Tried to instantiate an item instance from %s, but the definition conditions are not met."), *GetNameSafe(DefinitionClass));
        if (!OutFailureReason.IsValid())
            OutFailureReason = InventorySystemGameplayTags::TAG_Inventory_Failure_DefinitionRefused;
        return false;
    }
    // If the object has no storable fragment, it cannot be added to the inventory
    const UItemFragment_Storable* StorableFragment = CachedDefinition->FindFragmentByClass<UItemFragment_Storable>();
    if (!IsValid(StorableFragment))
    {
        UE_LOG(LogInventorySystem, Warning, TEXT("Tried to instantiate an item instance of %s but do not own UItemFragment_Storable fragment."), *GetNameSafe(CachedDefinition));
        OutFailureReason = InventorySystemGameplayTags::TAG_Inventory_Failure_NotStorable;
        return false;
    }
    // Check if the object is unique
    if (StorableFragment->IsUnique())
    {
        if (const FInventoryEntryHandle Handle = FindHandleOfType(DefinitionClass); Handle.IsValid())
        {
            // Allow if we can fit in the existing stack
            if (StorableFragment->CanStack() && (StorableFragment->MaxStackCount - Handle.StackCount <= InCount))
                return true;
            UE_LOG(LogInventorySystem, Warning, TEXT("Tried to instantiate a single item instance %s but another instance already exists."), *GetNameSafe(CachedDefinition));
            OutFailureReason = InventorySystemGameplayTags::TAG_Inventory_Failure_Uniqueness;
            return false;
        }
    }
    return true;
}
References UItemDefinition::CanBeGiven(), UItemFragment_Storable::CanStack(), UItemDefinition::FindFragmentByClass(), FindHandleOfType(), UItemFragment_Storable::IsUnique(), FInventoryEntryHandle::IsValid(), UItemFragment_Storable::MaxStackCount, and OwnerComponent.
Referenced by Add().
CreateItemInstance()
UItemInstance * FInventoryList::CreateItemInstance (const TSubclassOf< UItemDefinition > & DefinitionClass, int32 & Count) protected
Definition at line 296 of file InventoryList.cpp.
{
    AActor* OwnerActor = OwnerComponent->GetOwner();
    if (!OwnerActor->HasAuthority())
    {
        return nullptr;
    }
    // Get item definition instance
    UItemDefinition* CachedDefinition = OwnerComponent->GetCachedDefinition(DefinitionClass);
    const UItemFragment_Storable* StorableFragment = CachedDefinition->FindFragmentByClass<UItemFragment_Storable>();
    if (!IsValid(StorableFragment))
    {
        return nullptr;
    }
    // Create a new entry
    FInventoryEntry& Entry = Entries.AddDefaulted_GetRef();
    const int32 Index = Entries.Num();
    Entry.Instance = NewObject<UItemInstance>(OwnerActor);
    Entry.Instance->SetDefinition(CachedDefinition);
    Entry.StackCount = StorableFragment->CanStack() ? FMath::Min(Count, StorableFragment->MaxStackCount) : 1;
    Count -= Entry.StackCount;
    for (auto Fragment : CachedDefinition->Fragments)
    {
        if (IsValid(Fragment))
        {
            Fragment->OnInstanceCreated(Entry.Instance);
        }
    }
    Internal_OnEntryAdded(Index, Entry);
    MarkItemDirty(Entry);
    return Entry.Instance;
}
FindEntryOfType()
FInventoryEntry * FInventoryList::FindEntryOfType (const TSubclassOf< UItemDefinition > & ItemDefinition)
Finds the first entry of a specific item definition.
Parameters
ItemDefinition The item definition class to find.
Returns
The inventory entry if found, otherwise nullptr.
Definition at line 253 of file InventoryList.cpp.
{
    if (!IsValid(ItemDefinition))
    {
        return nullptr;
    }
    return Entries.FindByPredicate([ItemDefinition](const FInventoryEntry& Entry) { return Entry.Instance->GetDefinitionClass()->IsInA(ItemDefinition); });
}
References Entries.
FindHandleOfType()
FInventoryEntryHandle FInventoryList::FindHandleOfType (const TSubclassOf< UItemDefinition > & ItemDefinition)
Finds the handle of the first entry of a specific item definition.
Parameters
ItemDefinition The item definition class to find.
Returns
The inventory entry handle if found, otherwise an invalid handle.
Definition at line 198 of file InventoryList.cpp.
{
    if (!IsValid(ItemDefinition))
    {
        return {};
    }
    for (int Index = 0; Index < Entries.Num(); ++Index)
    {
        if (const FInventoryEntry& Entry = Entries[Index]; IsValid(Entry.Instance) && Entry.Instance->GetDefinitionClass() == ItemDefinition)
        {
            return FInventoryEntryHandle(Index, Entry);
        }
    }
    return {};
}
References Entries.
Referenced by CanAdd().
GetAllEntries()
TArray< FInventoryEntry * > FInventoryList::GetAllEntries () static
Gets all entries currently in the inventory
Returns
Array containing all inventory entries
See also
FInventoryEntry
Definition at line 282 of file InventoryList.cpp.
{
    TArray<FInventoryEntry*> InventoryEntries;
    // Pre-reserve memory for the array
    InventoryEntries.Reserve(InventoryEntries.Num());
    for (auto Entry : InventoryEntries)
    {
        InventoryEntries.Add(Entry);
    }
    return InventoryEntries;
}
GetAllHandles()
TArray< FInventoryEntryHandle > FInventoryList::GetAllHandles () const
Gets all handles in the inventory.
Returns
An array of all inventory entry handles.
Definition at line 235 of file InventoryList.cpp.
{
    TArray<FInventoryEntryHandle> Handles = {};
    // Pre-reserve memory for the array
    Handles.Reserve(Entries.Num());
    for (int32 Index = 0; Index < Entries.Num(); ++Index)
    {
        if (const FInventoryEntry& Entry = Entries[Index]; IsValid(Entry.Instance))
        {
            FInventoryEntryHandle Handle = FInventoryEntryHandle(Index, Entry);
            Handles.Add(Handle);
        }
    }
    return Handles;
}
References Entries.
GetEntriesOfType()
TArray< FInventoryEntry * > FInventoryList::GetEntriesOfType (const TSubclassOf< UItemDefinition > & ItemDefinition) static
Gets all entries matching the specified item definition
Parameters
ItemDefinition The item definition class to find
Returns
Array of inventory entries matching the definition
See also
FInventoryEntry
Definition at line 263 of file InventoryList.cpp.
{
    TArray<FInventoryEntry*> InventoryEntries = {};
    if (!IsValid(ItemDefinition))
    {
        return InventoryEntries;
    }
    for (auto Entry : InventoryEntries)
    {
        if (IsValid(Entry->Instance) && Entry->Instance->GetDefinitionClass()->IsInA(ItemDefinition))
        {
            InventoryEntries.Add(Entry);
        }
    }
    return InventoryEntries;
}
GetHandlesOfType()
TArray< FInventoryEntryHandle > FInventoryList::GetHandlesOfType (const TSubclassOf< UItemDefinition > & ItemDefinition)
Gets all handles of a specific item definition.
Parameters
ItemDefinition The item definition class to find.
Returns
An array of inventory entry handles.
Definition at line 215 of file InventoryList.cpp.
{
    TArray<FInventoryEntryHandle> Handles = {};
    if (!IsValid(ItemDefinition))
    {
        return Handles;
    }
    for (int32 Index = 0; Index < Entries.Num(); ++Index)
    {
        if (const FInventoryEntry& Entry = Entries[Index]; IsValid(Entry.Instance) && Entry.Instance->GetDefinitionClass()->IsInA(ItemDefinition))
        {
            FInventoryEntryHandle Handle = FInventoryEntryHandle(Index, Entry);
            Handles.Add(Handle);
        }
    }
    return Handles;
}
References Entries.
Internal_OnEntryAdded()
void FInventoryList::Internal_OnEntryAdded (int32 Index, const FInventoryEntry & Entry) const protected
Called when an entry is added.
Parameters
Index The index of the added entry.
Entry The added entry.
Definition at line 393 of file InventoryList.cpp.
{
    FInventoryChangeData Data;
    Data.Index = Index;
    Data.Instance = Entry.Instance;
    Data.ChangeType = EInventoryChangeType::Added;
    Data.OldCount = Entry.LastStackCount;
    Data.NewCount = Entry.StackCount;
    OwnerComponent->PostInventoryEntryAdded(Data);
    OwnerComponent->PostInventoryChanged(Data);
}
References FInventoryChangeData::ChangeType, FInventoryChangeData::Index, FInventoryChangeData::Instance, FInventoryChangeData::NewCount, FInventoryChangeData::OldCount, and OwnerComponent.
Internal_OnEntryChanged()
void FInventoryList::Internal_OnEntryChanged (int32 Index, const FInventoryEntry & Entry) const protected
Called when an entry is changed.
Parameters
Index The index of the changed entry.
Entry The changed entry.
Definition at line 380 of file InventoryList.cpp.
{
    FInventoryChangeData Data;
    Data.Index = Index;
    Data.Instance = Entry.Instance;
    Data.ChangeType = EInventoryChangeType::Modified;
    Data.OldCount = Entry.LastStackCount;
    Data.NewCount = Entry.StackCount;
    OwnerComponent->PostInventoryEntryChanged(Data);
    OwnerComponent->PostInventoryChanged(Data);
}
References FInventoryChangeData::ChangeType, FInventoryChangeData::Index, FInventoryChangeData::Instance, FInventoryChangeData::NewCount, FInventoryChangeData::OldCount, and OwnerComponent.
Referenced by Add().
Internal_OnEntryRemoved()
void FInventoryList::Internal_OnEntryRemoved (int32 Index, const FInventoryEntry & Entry) const protected
Called when an entry is removed.
Parameters
Index The index of the removed entry.
Entry The removed entry.
Definition at line 406 of file InventoryList.cpp.
{
    FInventoryChangeData Data;
    Data.Index = Index;
    Data.Instance = Entry.Instance;
    Data.ChangeType = EInventoryChangeType::Removed;
    Data.OldCount = Entry.LastStackCount;
    Data.NewCount = Entry.StackCount;
    OwnerComponent->PostInventoryEntryRemoved(Data);
    OwnerComponent->PostInventoryChanged(Data);
}
References FInventoryChangeData::ChangeType, FInventoryChangeData::Index, FInventoryChangeData::Instance, FInventoryChangeData::NewCount, FInventoryChangeData::OldCount, and OwnerComponent.
Referenced by Remove().
NetDeltaSerialize()
bool FInventoryList::NetDeltaSerialize (FNetDeltaSerializeInfo & DeltaParams) inline
Implements network delta serialization for the equipment list.
Definition at line 62 of file InventoryList.h.
{ return FastArrayDeltaSerialize<FInventoryEntry, FInventoryList>(Entries, DeltaParams, *this); }
References Entries.
PostReplicatedAdd()
void FInventoryList::PostReplicatedAdd (const TArrayView< int32 > AddedIndices, int32 FinalSize)
Definition at line 37 of file InventoryList.cpp.
{
    for (const int32 Index : AddedIndices)
    {
        if (Entries.IsValidIndex(Index))
        {
            FInventoryEntry& Entry = Entries[Index];
            Entry.LastStackCount = Entry.StackCount;
            Internal_OnEntryAdded(Index, Entry);
        }
    }
}
PostReplicatedChange()
void FInventoryList::PostReplicatedChange (const TArrayView< int32 > ChangedIndices, int32 FinalSize)
Definition at line 51 of file InventoryList.cpp.
{
    for (const int32 Index : ChangedIndices)
    {
        if (Entries.IsValidIndex(Index))
        {
            FInventoryEntry& Entry = Entries[Index];
            ensureMsgf(Entry.LastStackCount != INDEX_NONE, TEXT("LastStackCount is invalid (INDEX_NONE) for entry at index %d. Should replicate this change"), Index);
            Internal_OnEntryChanged(Index, Entry);
            Entry.LastStackCount = Entry.StackCount;
        }
    }
}
PreReplicatedRemove()
void FInventoryList::PreReplicatedRemove (const TArrayView< int32 > RemovedIndices, int32 FinalSize)
Definition at line 23 of file InventoryList.cpp.
{
    for (const int32 Index : RemovedIndices)
    {
        if (Entries.IsValidIndex(Index))
        {
            FInventoryEntry& Entry = Entries[Index];
            Entry.LastStackCount = 0;
            Internal_OnEntryRemoved(Index, Entry);
        }
    }
}
Remove()
void FInventoryList::Remove (UItemInstance * Instance, FGameplayTag & OutFailureReason)
Removes an item from the inventory.
Parameters
Instance The item instance to remove.
OutFailureReason
Definition at line 146 of file InventoryList.cpp.
{
    for (auto EntryIterator = Entries.CreateIterator(); EntryIterator; ++EntryIterator)
    {
        if (FInventoryEntry Entry = *EntryIterator; Entry.Instance == Instance)
        {
            Internal_OnEntryRemoved(EntryIterator.GetIndex(), Entry);
            EntryIterator.RemoveCurrent();
            MarkArrayDirty();
        }
    }
}
References Entries, and Internal_OnEntryRemoved().
Friends And Related Symbol Documentation
UInventorySystemComponent
friend class UInventorySystemComponent friend
Definition at line 50 of file InventoryList.h.
Member Data Documentation
Entries
TArray<FInventoryEntry> FInventoryList::Entries protected
Array of inventory entries managed by this list
Definition at line 158 of file InventoryList.h.
Referenced by Add(), FindEntryOfType(), FindHandleOfType(), GetAllHandles(), GetHandlesOfType(), NetDeltaSerialize(), and Remove().
FInventoryEntry
friend FInventoryList::FInventoryEntry
Definition at line 51 of file InventoryList.h.
OwnerComponent
TObjectPtr<UInventorySystemComponent> FInventoryList::OwnerComponent = nullptr protected
The inventory system component that owns this list. Not replicated
Definition at line 162 of file InventoryList.h.
Referenced by Add(), CanAdd(), Internal_OnEntryAdded(), Internal_OnEntryChanged(), and Internal_OnEntryRemoved().
The documentation for this class was generated from the following files:
Source/InventorySystemCore/Public/Data/InventoryList.h
Source/InventorySystemCore/Private/Data/InventoryList.cpp