name: Deploy doxygen documentation

on:
  push:
    branches: [main] # ou la branche que tu utilises

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate documentation
        run: doxygen Doxyfile # adapte le chemin si besoin

      - name: Deploy on Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html # adapte le chemin si besoin